export const uiContent = {
  en: {
    home: "Home",
    calculators: "Calculators",
    blog: "Blog",
    about: "About",
    contact: "Contact",
    company: "Company",
    legal: "Legal",
    privacyPolicy: "Privacy Policy",
    terms: "Terms of Service",
    disclaimer: "Disclaimer",
    footerTagline: "Free, fun, name-based compatibility calculators for entertainment purposes.",
    footerCopyright: "All results are for entertainment purposes only.",
    toolNames: {
      love: "Love Calculator",
      flames: "FLAMES Calculator",
      soulmate: "Soulmate Calculator",
      marriage: "Marriage Compatibility",
      friendship: "Friendship Calculator",
      crush: "Crush Calculator",
    },
    toolDescriptions: {
      flames: "Try the classic FLAMES relationship game using two names.",
      soulmate: "Explore a fun soulmate-style compatibility result.",
      marriage: "Explore name-based marriage compatibility for entertainment.",
      friendship: "Check a fun friendship compatibility score.",
      crush: "See what your names generate in a fun crush compatibility test.",
    },
    blogTitle: "Blog",
    blogSub: "Fun, honest reads about numerology, compatibility, and the games behind our calculators.",
    blogPosts: [
      { slug: "what-is-numerology", title: "What Is Numerology? A Simple Guide for Beginners", excerpt: "Curious how numerology turns names into numbers? Here's an easy, honest breakdown of the concept behind tools like our love calculator." },
      { slug: "love-calculator-vs-real-compatibility", title: "Love Calculator vs Real Compatibility: What's the Difference?", excerpt: "A fun percentage is not the same as real compatibility. Here's what actually matters in a relationship, beyond any online score." },
      { slug: "flames-game-history", title: "The History of the FLAMES Game — Where Did It Come From?", excerpt: "Long before online calculators, FLAMES was a paper-and-pen game passed between friends. Here's where it came from and how it works." },
      { slug: "fun-things-to-do-with-your-crush-name", title: "10 Fun Things to Do With Your Crush's Name (Besides a Love Calculator)", excerpt: "Beyond running a love calculator, here are other lighthearted, low-pressure ways to have fun with a crush's name." },
    ],
  },
  hi: {
    home: "होम",
    calculators: "कैलकुलेटर",
    blog: "ब्लॉग",
    about: "हमारे बारे में",
    contact: "संपर्क करें",
    company: "कंपनी",
    legal: "कानूनी",
    privacyPolicy: "प्राइवेसी पॉलिसी",
    terms: "सेवा की शर्तें",
    disclaimer: "अस्वीकरण",
    footerTagline: "मुफ़्त, मज़ेदार, नाम-आधारित कम्पैटिबिलिटी कैलकुलेटर, केवल मनोरंजन के लिए।",
    footerCopyright: "सभी परिणाम केवल मनोरंजन के उद्देश्य से हैं।",
    toolNames: {
      love: "लव कैलकुलेटर",
      flames: "FLAMES कैलकुलेटर",
      soulmate: "सोलमेट कैलकुलेटर",
      marriage: "मैरिज कम्पैटिबिलिटी",
      friendship: "फ्रेंडशिप कैलकुलेटर",
      crush: "क्रश कैलकुलेटर",
    },
    toolDescriptions: {
      flames: "दो नामों के साथ क्लासिक FLAMES रिलेशनशिप गेम आज़माएं।",
      soulmate: "एक मज़ेदार सोलमेट-स्टाइल कम्पैटिबिलिटी परिणाम एक्सप्लोर करें।",
      marriage: "मनोरंजन के लिए नाम-आधारित मैरिज कम्पैटिबिलिटी एक्सप्लोर करें।",
      friendship: "एक मज़ेदार फ्रेंडशिप कम्पैटिबिलिटी स्कोर जांचें।",
      crush: "देखें आपके नाम एक मज़ेदार क्रश कम्पैटिबिलिटी टेस्ट में क्या बताते हैं।",
    },
    blogTitle: "ब्लॉग",
    blogSub: "न्यूमेरोलॉजी, कम्पैटिबिलिटी और हमारे कैलकुलेटर के पीछे के खेलों के बारे में मज़ेदार, ईमानदार लेख।",
    blogPosts: [
      { slug: "what-is-numerology", title: "न्यूमेरोलॉजी क्या है? शुरुआती लोगों के लिए एक आसान गाइड", excerpt: "जानना चाहते हैं न्यूमेरोलॉजी नामों को नंबरों में कैसे बदलती है? यहां एक आसान, ईमानदार व्याख्या है।" },
      { slug: "love-calculator-vs-real-compatibility", title: "लव कैलकुलेटर बनाम असली कम्पैटिबिलिटी: क्या फर्क है?", excerpt: "एक मज़ेदार प्रतिशत असली कम्पैटिबिलिटी जैसा नहीं है। जानें रिश्ते में असल में क्या मायने रखता है।" },
      { slug: "flames-game-history", title: "FLAMES गेम का इतिहास — यह कहां से आया?", excerpt: "ऑनलाइन कैलकुलेटर से बहुत पहले, FLAMES एक पेन-पेपर वाला खेल था। जानें यह कहां से आया।" },
      { slug: "fun-things-to-do-with-your-crush-name", title: "आपके क्रश के नाम के साथ करने के लिए 10 मज़ेदार चीज़ें", excerpt: "लव कैलकुलेटर के अलावा, यहां क्रश के नाम के साथ मज़े करने के और तरीके हैं।" },
    ],
  },
};
