export const numerologyBlogContent = {
  en: {
    title: "What Is Numerology? A Simple Guide for Beginners",
    p1Pre: "If you've ever used a",
    p1Link: "love calculator by name",
    p1Post: "and wondered how it turns two names into a percentage, the answer usually traces back to numerology. It's a concept that shows up in everything from name generators to birthday readings, so it's worth understanding in plain terms.",
    h2_1: "The Basic Idea Behind Numerology",
    p2: "Numerology is a belief system that assigns meaning to numbers, often by converting letters or dates into numeric values. The core idea is that numbers carry symbolic weight, and that patterns in those numbers can say something about a person, a name, or an event.",
    h2_2: "How Letters Become Numbers",
    p3: "One of the most common systems assigns each letter of the alphabet a number from 1 to 9, repeating the sequence for later letters. Once every letter in a name has a number, those numbers get added together and reduced down to a single digit — a process called digit reduction.",
    letterTableTitle: "Pythagorean Numerology Letter Chart",
    letterTableHeaders: ["Number", "Letters"],
    letterTableRows: [
      ["1", "A, J, S"],
      ["2", "B, K, T"],
      ["3", "C, L, U"],
      ["4", "D, M, V"],
      ["5", "E, N, W"],
      ["6", "F, O, X"],
      ["7", "G, P, Y"],
      ["8", "H, Q, Z"],
      ["9", "I, R"],
    ],
    p4: "For example, imagine a name whose letters add up to 47. To reduce that, you'd add 4 + 7 to get 11, then reduce again by adding 1 + 1 to land on 2. That final single digit is treated as the name's \"numerology number.\"",
    h2_3: "How This Connects to Love Calculators",
    p5Pre: "A typical",
    p5Link: "name love calculator",
    p5Post: "takes this same letter-to-number process, applies it to two names separately, and then combines the two results using its own formula to produce a compatibility percentage. Some tools, including ours, also let you add a date of birth.",
    h2_4: "Is Numerology Scientifically Proven?",
    p6: "No. Numerology is a belief-based, divinatory practice, not a scientifically validated field. There's no peer-reviewed evidence that converting letters into numbers reveals anything meaningful about compatibility. That doesn't make it any less fun — it just means it should be treated as entertainment rather than fact.",
    h2_5: "Why We're Upfront About This",
    p7Pre: "We think tools built around numerology — like our",
    p7Link1: "Soulmate Calculator",
    p7Mid: "or",
    p7Link2: "FLAMES Calculator",
    p7Post: "— are most enjoyable when people understand exactly what they are: a fun, numbers-based game, not a scientific test.",

    h2_6: "A Brief History of Numerology",
    p8: "Numerology in some form has existed for thousands of years, with roots often traced back to ancient Babylon, Greece, and Egypt. The Greek philosopher Pythagoras is frequently credited with popularizing the idea that numbers hold symbolic and even mystical meaning, which is why the letter-to-number system used in most modern love calculators is often called \"Pythagorean numerology,\" even though it has evolved considerably since his time. Different cultures developed their own parallel systems — Chaldean numerology, for example, assigns different values to letters than the Pythagorean system does, which is one reason two different love calculators can sometimes produce different scores for the exact same two names.",
    p9: "By the 19th and 20th centuries, numerology had become a popular part of Western esoteric and New Age culture, appearing alongside astrology, tarot, and palmistry as a way for people to explore questions about personality, timing, and relationships outside of mainstream science. That same cultural thread is what eventually led to numerology being folded into early \"name compatibility\" games and, much later, into online calculators like the ones on this site.",

    h2_7: "Common Numerology Terms You Might See",
    p10: "If you spend any time reading about numerology, a few terms come up again and again. A \"Life Path Number\" is typically calculated from a person's full date of birth and is treated as a kind of core personality number in most numerology systems. A \"Destiny Number\" or \"Expression Number\" is usually calculated from the letters in a person's full name, similar to the process our calculators use. A \"Soul Urge Number\" focuses only on the vowels in a name, based on the idea that vowels represent inner desires while consonants represent outward expression. Our calculators keep things simpler than a full traditional numerology reading — we focus on a single combined compatibility number rather than generating a multi-page personality profile — but it's useful to know these terms exist if you want to explore numerology further on your own.",

    h2_8: "Numerology vs Astrology: What's the Difference?",
    p11: "People sometimes lump numerology and astrology together, but they work differently under the hood. Astrology bases its interpretations on the position of celestial bodies at the moment of a person's birth, while numerology works purely with numbers derived from names and dates, with no reference to the sky at all. Both are considered pseudoscientific by mainstream researchers, and both remain popular precisely because they're accessible — you don't need a telescope or a birth chart calculation service to try numerology, just a name and, optionally, a date of birth, which is part of why it translates so naturally into a simple web-based love calculator.",

    h2_9: "Should You Take Numerology Seriously?",
    p12: "That's really up to you. Some people enjoy numerology as a lighthearted framework for reflecting on relationships, decisions, or timing, similar to how many people enjoy horoscopes without treating them as literal fact. Others prefer to treat it purely as entertainment, the same way you might enjoy a fortune cookie without expecting it to predict your actual future. What we'd caution against is using a numerology-based score — from this site or any other — to make a real decision about a relationship, a marriage, or a major life choice. The numbers are consistent and fun to play with, but they were never designed to replace judgment, communication, or getting to know someone as a real person.",

    h2_10: "Try Calculating Your Own Numerology Number",
    p13: "If you'd like to see the letter-to-number process for yourself before running a full compatibility check, you can do a simplified version by hand. Write out your first name, then look up each letter's number using the 1–9 cycle described earlier (A=1, B=2, C=3, and so on, restarting after I). Add all those numbers together, then keep adding the digits of the result together until you land on a single number between 1 and 9. For example, a short four-letter name might add up to 19 on the first pass; adding 1 + 9 gives 10, and adding 1 + 0 gives a final number of 1. Every name eventually reduces down to one of nine possible numbers this way, which is part of why numerology enthusiasts talk about each number having its own personality or theme.",
    p14: "Doing this by hand is a fun way to understand exactly what's happening before you let a calculator do it instantly. It also explains why two very different-looking names can sometimes produce the same underlying numerology number — the specific letters matter less than how their values add up and reduce in the end.",

    h2_11: "Numerology in Pop Culture and Everyday Life",
    p15: "Beyond love calculators, numerology shows up in more places than people often realize. Some couples choose wedding dates based on numbers they consider auspicious. Some parents research the numerology of a baby name before finalizing it, treating it similarly to checking a name's meaning or origin. Numbers like 7, 11, and 22 are frequently singled out in numerology circles as having special significance, which is part of why you'll see phrases like \"angel numbers\" trending on social media. None of this is scientifically established, but it says something about how enduring the appeal of number-based meaning-making really is — and it's exactly that same appeal that makes a simple love calculator by name fun to try, even for people who don't consider themselves \"into\" numerology at all.",

    ctaPre: "Ready to try it yourself? Head back to the",
    ctaLink: "main Love Calculator",
    ctaPost: "and see what your name adds up to.",
  },
  hi: {
    title: "न्यूमेरोलॉजी क्या है? शुरुआती लोगों के लिए एक आसान गाइड",
    p1Pre: "अगर आपने कभी",
    p1Link: "लव कैलकुलेटर बाय नेम",
    p1Post: "इस्तेमाल किया है और सोचा है कि यह दो नामों को प्रतिशत में कैसे बदलता है, तो इसका जवाब आमतौर पर न्यूमेरोलॉजी में मिलता है। यह एक ऐसा कॉन्सेप्ट है जो नेम जनरेटर से लेकर बर्थडे रीडिंग तक हर जगह दिखता है।",
    h2_1: "न्यूमेरोलॉजी के पीछे की मूल सोच",
    p2: "न्यूमेरोलॉजी एक विश्वास प्रणाली है जो नंबरों को अर्थ देती है, अक्सर अक्षरों या तारीखों को नंबरों में बदलकर। मूल विचार यह है कि नंबरों में एक प्रतीकात्मक महत्व होता है, और उन नंबरों के पैटर्न किसी व्यक्ति, नाम या घटना के बारे में कुछ बता सकते हैं।",
    h2_2: "अक्षर नंबर कैसे बनते हैं",
    p3: "सबसे आम प्रणालियों में से एक हर अक्षर को 1 से 9 तक एक नंबर देती है, और आगे के अक्षरों के लिए यह क्रम दोहराया जाता है। एक बार जब नाम के हर अक्षर को नंबर मिल जाता है, उन्हें जोड़ा जाता है और एक अंक तक घटाया जाता है।",
    p4: "उदाहरण के लिए, मान लीजिए किसी नाम के अक्षर जुड़कर 47 बनते हैं। इसे घटाने के लिए, 4 + 7 = 11, फिर 1 + 1 = 2 करके अंतिम अंक निकाला जाता है। यही अंतिम अंक नाम का \"न्यूमेरोलॉजी नंबर\" माना जाता है।",
    h2_3: "यह लव कैलकुलेटर से कैसे जुड़ता है",
    p5Pre: "एक सामान्य",
    p5Link: "नेम लव कैलकुलेटर",
    p5Post: "यही अक्षर-से-नंबर प्रक्रिया इस्तेमाल करता है, इसे दोनों नामों पर अलग-अलग लागू करता है, फिर अपने फॉर्मूले से दोनों परिणामों को मिलाकर एक कम्पैटिबिलिटी प्रतिशत बनाता है।",
    h2_4: "क्या न्यूमेरोलॉजी वैज्ञानिक रूप से सिद्ध है?",
    p6: "नहीं। न्यूमेरोलॉजी एक विश्वास-आधारित प्रणाली है, कोई वैज्ञानिक रूप से मान्य क्षेत्र नहीं। इसका मतलब यह नहीं कि यह कम मज़ेदार है — बस इसे तथ्य की बजाय मनोरंजन के रूप में देखा जाना चाहिए।",
    h2_5: "हम इस बारे में स्पष्ट क्यों हैं",
    p7Pre: "हमारा मानना है कि न्यूमेरोलॉजी पर आधारित टूल — जैसे हमारा",
    p7Link1: "सोलमेट कैलकुलेटर",
    p7Mid: "या",
    p7Link2: "FLAMES कैलकुलेटर",
    p7Post: "— सबसे ज़्यादा मज़ेदार तब होते हैं जब लोग समझते हैं कि ये असल में क्या हैं: एक मज़ेदार, नंबर-आधारित खेल, कोई वैज्ञानिक टेस्ट नहीं।",
    ctaPre: "खुद आज़माना चाहते हैं? वापस",
    ctaLink: "मुख्य लव कैलकुलेटर",
    ctaPost: "पर जाएं और देखें आपका नाम क्या बताता है।",
  },
};

export const compatibilityBlogContent = {
  en: {
    title: "Love Calculator vs Real Compatibility: What's the Difference?",
    p1Pre: "It's easy to type two names into a",
    p1Link: "love calculator by name",
    p1Post: ", get a percentage, and wonder how seriously to take it. The honest answer: not very seriously, and that's actually part of the appeal.",
    h2_1: "What a Love Calculator Actually Measures",
    p2: "A love calculator measures exactly one thing: how two names combine under a numerology-style formula. It doesn't know anything about how two people communicate, handle conflict, or treat each other day to day.",
    measureTableTitle: "What Gets Measured vs What Actually Matters",
    measureTableHeaders: ["A Love Calculator Measures", "Real Compatibility Depends On"],
    measureTableRows: [
      ["Letters in each name", "How you communicate under stress"],
      ["A fixed numerology formula", "Shared values and life goals"],
      ["A static percentage", "Trust built over time"],
      ["Nothing about behavior", "How you handle conflict and repair"],
      ["Nothing about history", "Consistency and follow-through"],
    ],
    h2_2: "What Real Compatibility Actually Depends On",
    p3: "Real compatibility is built from dozens of small, ongoing factors that no calculator can see:",
    list: [
      "How well you communicate, especially during disagreements",
      "Whether your core values and life goals line up",
      "How you each handle stress, and how you support each other",
      "Trust, honesty, and consistency over time",
      "Shared humor, curiosity, and everyday compatibility",
    ],
    p4: "None of these can be reduced to a percentage, and none show up in a name-based calculation.",
    h2_3: "So Why Do People Still Enjoy Love Calculators?",
    p5Pre: "Because they're fun, fast, and low-stakes. Nobody sits down at a",
    p5Link: "Crush Calculator",
    p5Post: "expecting a scientific verdict — it's more like a fortune cookie than a diagnosis.",
    h2_4: "A Simple Rule of Thumb",
    p6: "Enjoy the score, share it if it's fun, and then let real conversations — not a number — guide anything that actually matters in your relationship.",

    h2_5: "What Psychologists Actually Say About Compatibility",
    p7: "Relationship researchers have spent decades studying what actually predicts whether a couple stays happy long-term, and the findings look nothing like a name-based percentage. Long-running studies on married couples point to factors like how partners handle conflict, whether they turn toward each other for support during stress, shared appreciation and respect, and the ability to repair after an argument rather than avoiding disagreement altogether. None of these can be measured from two names — they only reveal themselves through actual interaction over time, which is exactly why no online tool, however sophisticated, can substitute for real observation of a real relationship.",

    h2_6: "Why We Still Think Love Calculators Are Worth Using",
    p8: "None of this means love calculators are pointless — they're just not trying to do what a psychologist's research does, and that's fine. A love calculator is closer to a party game than a diagnostic tool. It gives people a shared, low-stakes moment to laugh about, compare with friends, or use as a light conversation starter with a new crush. The key is keeping expectations calibrated: enjoy the percentage the same way you'd enjoy a fortune cookie message, without mistaking either one for actual insight into your relationship's future.",

    h2_7: "Red Flags a Love Calculator Will Never Catch",
    p9: "Because a love calculator only looks at letters in a name, there's a long list of real relationship signals it simply cannot see. It can't tell you whether someone listens when you're upset, whether they follow through on what they say, how they handle money, or how they treat people who can't do anything for them. A high score can't rule out incompatibility, and a low score can't manufacture chemistry that isn't there. If you're genuinely trying to evaluate a relationship, these are the kinds of things worth paying attention to — not a percentage generated from two names.",

    h2_8: "Using a Love Calculator the Healthy Way",
    p10: "The healthiest way to use a love calculator is to treat the number itself as disposable. Run it, laugh at it, screenshot it if it's funny, and move on. Don't let a low score create doubt about someone you already trust, and don't let a high score talk you into ignoring real concerns about someone you don't. Used this way — as entertainment rather than evidence — a love calculator can be a fun, harmless part of getting to know someone, which is exactly what it was designed to be in the first place.",

    ctaPre: "Want to try a different angle on the same names? Check out our",
    ctaLink1: "FLAMES Calculator",
    ctaMid: "or head back to the",
    ctaLink2: "main Love Calculator",
    ctaPost: ".",
  },
  hi: {
    title: "लव कैलकुलेटर बनाम असली कम्पैटिबिलिटी: क्या फर्क है?",
    p1Pre: "किसी",
    p1Link: "लव कैलकुलेटर बाय नेम",
    p1Post: "में दो नाम डालना, एक प्रतिशत पाना, और सोचना कि इसे कितनी गंभीरता से लें आसान है। ईमानदार जवाब: ज़्यादा गंभीरता से नहीं, और यही इसकी खासियत भी है।",
    h2_1: "लव कैलकुलेटर असल में क्या मापता है",
    p2: "लव कैलकुलेटर सिर्फ एक चीज़ मापता है: दो नाम न्यूमेरोलॉजी फॉर्मूले के तहत कैसे मिलते हैं। इसे यह नहीं पता कि दो लोग कैसे बातचीत करते हैं या एक-दूसरे के साथ कैसा व्यवहार करते हैं।",
    h2_2: "असली कम्पैटिबिलिटी असल में किस पर निर्भर करती है",
    p3: "असली कम्पैटिबिलिटी दर्जनों छोटे, लगातार चलने वाले कारकों से बनती है जिन्हें कोई कैलकुलेटर नहीं देख सकता:",
    list: [
      "आप कितनी अच्छी तरह बातचीत करते हैं, खासकर असहमति में",
      "क्या आपके मूल मूल्य और जीवन लक्ष्य मेल खाते हैं",
      "आप तनाव कैसे संभालते हैं और एक-दूसरे को कैसे सहारा देते हैं",
      "समय के साथ भरोसा, ईमानदारी और निरंतरता",
      "साझा हास्य, जिज्ञासा, और रोज़मर्रा की कम्पैटिबिलिटी",
    ],
    p4: "इनमें से कुछ भी प्रतिशत में नहीं बदला जा सकता, और न ही किसी नाम-आधारित गणना में दिखता है।",
    h2_3: "फिर भी लोग लव कैलकुलेटर क्यों पसंद करते हैं?",
    p5Pre: "क्योंकि ये मज़ेदार, तेज़ और बिना किसी जोखिम के हैं। कोई भी",
    p5Link: "क्रश कैलकुलेटर",
    p5Post: "से वैज्ञानिक फैसले की उम्मीद नहीं रखता — यह किसी डायग्नोसिस से ज़्यादा फॉर्च्यून कुकी जैसा है।",
    h2_4: "एक आसान नियम",
    p6: "स्कोर को एन्जॉय करें, अगर मज़ेदार लगे तो शेयर करें, और फिर असली बातचीत को ही अपने रिश्ते की असली बातों का मार्गदर्शक बनने दें, किसी नंबर को नहीं।",
    ctaPre: "उन्हीं नामों पर कुछ अलग आज़माना चाहते हैं? हमारा",
    ctaLink1: "FLAMES कैलकुलेटर",
    ctaMid: "देखें या वापस",
    ctaLink2: "मुख्य लव कैलकुलेटर",
    ctaPost: "पर जाएं।",
  },
};

export const flamesHistoryBlogContent = {
  en: {
    title: "The History of the FLAMES Game — Where Did It Come From?",
    p1Pre: "Long before anyone typed two names into an online",
    p1Link: "FLAMES Calculator",
    p1Post: ", the game was played the old-fashioned way — with a pen, paper, and a bit of patience.",
    h2_1: "A Playground Classic",
    p2: "FLAMES — short for Friends, Lovers, Affectionate, Marriage, Enemies, Siblings — traditionally spread as a schoolyard game. Two people would write out their names, cross out matching letters by hand, count what was left, and count through the letters F-L-A-M-E-S until one remained.",
    flamesTableTitle: "What Each FLAMES Letter Means",
    flamesTableHeaders: ["Letter", "Meaning"],
    flamesTableRows: [
      ["F", "Friends"],
      ["L", "Lovers"],
      ["A", "Affectionate"],
      ["M", "Marriage"],
      ["E", "Enemies"],
      ["S", "Siblings"],
    ],
    h2_2: "Why It Became So Popular",
    p3: "Part of the appeal was how quick and visual it was. Unlike a full percentage-based love calculator, FLAMES gave a single, easy-to-remember word as an answer. It also worked for more than just crushes.",
    h2_3: "From Paper to Pixels",
    p4Pre: "As online tools became common, FLAMES was one of the first \"love games\" to be digitized. Today's",
    p4Link: "FLAMES Calculator",
    p4Post: "runs the exact same letter-cancelling, letter-counting process instantly, without needing a pen or paper.",
    h2_4: "Is FLAMES Still Just for Fun?",
    p5: "Yes, and that hasn't changed. FLAMES has never been a scientifically validated relationship test — it's always been a lighthearted game, whether played on a napkin in the 90s or on a phone today.",

    h2_5: "How FLAMES Spread Around the World",
    p6: "Like many playground games, FLAMES doesn't have a single documented inventor or publication date — it spread the way folklore usually does, passed from friend to friend and classroom to classroom long before anyone thought to write it down. Regional variations popped up over the decades: some versions use slightly different words for the letters, some groups play with three names instead of two to include a rival or friend, and some cultures blend FLAMES-style letter-cancelling with their own local numerology or fortune-telling traditions. What's stayed consistent across almost every version is the core mechanic — cancel matching letters, count what's left, count through a set of category letters until one remains.",

    h2_6: "Why a Game With No Official Rules Still Feels Consistent",
    p7: "One interesting thing about FLAMES is that despite having no official publisher, rulebook, or governing body, the core mechanic has stayed remarkably consistent across generations and regions. That's likely because the method is simple enough to remember and teach on the spot — anyone who's played it once can teach a friend in under a minute, which is exactly the kind of game that survives purely through word of mouth. It's a good example of how a simple, repeatable algorithm can become genuinely viral long before the internet existed to help it spread.",

    h2_7: "FLAMES and the Rise of Online Love Games",
    p8: "FLAMES was part of a broader wave of simple, name-based \"love games\" that existed in playground culture well before the web — heart-shaped doodles with initials, folded paper fortune tellers (sometimes called \"cootie catchers\"), and various counting rhymes all served a similar social function: giving friends a low-stakes, slightly silly way to talk about crushes without having to say anything directly. When these games moved online in the early 2000s and 2010s, FLAMES translated especially well because its output — a single word like \"Friends\" or \"Lovers\" — is inherently shareable and screenshot-friendly, which matters a lot in an era of social media.",

    h2_8: "Trying FLAMES Today",
    p9: "The appeal of FLAMES hasn't really changed since its playground days — it's still fast, still visual, and still works just as well with a best friend's name as it does with a crush's. The only real difference is that the counting now happens instantly instead of by hand, and the result is easy to screenshot and send to a group chat instead of being scribbled on the corner of a notebook page.",

    ctaPre: "Curious what your names spell out? Try the",
    ctaLink1: "FLAMES Calculator",
    ctaMid: "or compare it with a percentage-based result on our",
    ctaLink2: "main Love Calculator",
    ctaPost: ".",
  },
  hi: {
    title: "FLAMES गेम का इतिहास — यह कहां से आया?",
    p1Pre: "किसी के भी ऑनलाइन",
    p1Link: "FLAMES कैलकुलेटर",
    p1Post: "में दो नाम डालने से बहुत पहले, यह खेल पुराने तरीके से खेला जाता था — पेन, पेपर और थोड़े धैर्य के साथ।",
    h2_1: "एक स्कूल का क्लासिक खेल",
    p2: "FLAMES — फ्रेंड्स, लवर्स, अफेक्शनेट, मैरिज, एनिमीज़, सिबलिंग्स का संक्षिप्त रूप — पारंपरिक रूप से एक स्कूली खेल की तरह फैला। दो लोग अपने नाम लिखते, मिलते-जुलते अक्षरों को हाथ से काटते, बचे हुए को गिनते, और F-L-A-M-E-S में गिनती करते जब तक एक अक्षर न बचे।",
    h2_2: "यह इतना लोकप्रिय क्यों हुआ",
    p3: "इसकी खासियत यह थी कि यह कितना तेज़ और विज़ुअल था। पूरे प्रतिशत-आधारित लव कैलकुलेटर के उलट, FLAMES एक आसानी से याद रहने वाला शब्द जवाब देता था।",
    h2_3: "पेपर से पिक्सल तक",
    p4Pre: "जैसे-जैसे ऑनलाइन टूल आम हुए, FLAMES डिजिटल होने वाले पहले \"लव गेम्स\" में से एक था। आज का",
    p4Link: "FLAMES कैलकुलेटर",
    p4Post: "वही अक्षर-काटने, अक्षर-गिनने की प्रक्रिया तुरंत करता है, बिना पेन-पेपर के।",
    h2_4: "क्या FLAMES अभी भी सिर्फ मज़े के लिए है?",
    p5: "हाँ, और यह नहीं बदला। FLAMES कभी भी वैज्ञानिक रूप से प्रमाणित रिश्ता परीक्षण नहीं रहा — यह हमेशा से एक हल्का-फुल्का खेल रहा है, चाहे 90 के दशक में नैपकिन पर खेला गया हो या आज फोन पर।",
    ctaPre: "जानना चाहते हैं आपके नाम क्या बताते हैं? आज़माएं",
    ctaLink1: "FLAMES कैलकुलेटर",
    ctaMid: "या हमारे",
    ctaLink2: "मुख्य लव कैलकुलेटर",
    ctaPost: "पर प्रतिशत-आधारित परिणाम से तुलना करें।",
  },
};

export const funThingsBlogContent = {
  en: {
    title: "10 Fun Things to Do With Your Crush's Name (Besides a Love Calculator)",
    p1Pre: "Running your crush's name through our",
    p1Link: "Crush Calculator",
    p1Post: "is a great start, but if you're looking for more lighthearted ways to pass the time, here are ten more fun, low-pressure ideas.",
    introH2: "Why People Love Playing With Names",
    introP: "There's something universally fun about seeing your name paired with someone else's — it's harmless, it's quick, and it doesn't require telling anyone how you actually feel. That's probably why name-based games like these have survived for generations, long before the internet turned them into instant, one-tap tools. Below are ten easy ways to keep the fun going beyond a single percentage.",
    summaryTableTitle: "Quick Summary of All 10 Ideas",
    summaryTableHeaders: ["#", "Idea"],
    summaryTableRows: [
      ["1", "Try the FLAMES Game"],
      ["2", "Check a Soulmate-Style Score"],
      ["3", "Compare Results With Friends"],
      ["4", "See What Marriage Compatibility Says"],
      ["5", "Learn the Numerology Behind It"],
      ["6", "Try Adding a Birthday"],
      ["7", "Share the Result on WhatsApp"],
      ["8", "Download and Save the Result"],
      ["9", "Run It Again With a Nickname"],
      ["10", "Remember It's Just for Fun"],
    ],
    items: [
      { h: "1. Try the FLAMES Game", pPre: "Instead of a percentage, get a category — Friends, Lovers, Affectionate, Marriage, Enemies, or Siblings — with our", link: "FLAMES Calculator", href: "/tools/flames-calculator", pPost: ".", pExtra: "It only takes a few seconds, and because the result is a single word instead of a number, it's often even easier to share in a group chat without it feeling too serious." },
      { h: "2. Check a Soulmate-Style Score", pPre: "Curious about a deeper connection angle? The", link: "Soulmate Calculator", href: "/tools/soulmate-calculator", pPost: "uses the same math with a more romantic framing.", pExtra: "Running the same two names through both the Love Calculator and the Soulmate Calculator can be a fun way to see how differently the same numbers can be framed." },
      { h: "3. Compare Results With Friends", pPre: "Run the same crush's name against your friends' names too — just for laughs, and to compare who \"wins\" the highest score.", link: null, pExtra: "This works especially well in a group setting, where everyone can take turns typing in the same crush's name and comparing notes afterward." },
      { h: "4. See What Marriage Compatibility Says", pPre: "Jump straight to the long-term hypothetical with our", link: "Marriage Compatibility Calculator", href: "/tools/marriage-compatibility", pPost: "— purely for fun, of course.", pExtra: "It's a popular one to try with a partner you're already dating, just to see what a more \"official\" sounding result looks like." },
      { h: "5. Learn the Numerology Behind It", pPre: "If you're curious how the numbers actually work, our", link: "numerology guide", href: "/blog/what-is-numerology", pPost: "breaks it down simply.", pExtra: "Understanding the letter-to-number process can make the whole experience more interesting, since you'll actually understand why a particular score came out the way it did." },
      { h: "6. Try Adding a Birthday", pPre: "Most of our calculators let you optionally add both dates of birth for an extra numerology layer — see how much the result shifts.", link: null, pExtra: "Some people like to run the calculation twice — once with just names, once with birthdays added — to compare the two versions side by side." },
      { h: "7. Share the Result on WhatsApp", pPre: "Every result comes with a one-tap WhatsApp share button, so you can send your score to a friend (or even your crush, if you're feeling bold).", link: null, pExtra: "Because the share message includes the score and a link back to the site, whoever receives it can try the calculator themselves right away." },
      { h: "8. Download and Save the Result", pPre: "Want to keep a copy? Every result can be downloaded as an image to save or share elsewhere.", link: null, pExtra: "This is handy if you want to post it to an Instagram story or keep it in your camera roll as a fun inside joke." },
      { h: "9. Run It Again With a Nickname", pPre: "Try the calculation again using a nickname instead of a full name — since the formula is letter-based, even small changes can shift the score.", link: null, pExtra: "This is a fun way to see how sensitive the formula really is, and it often becomes its own little game of trying every possible variation of a name." },
      { h: "10. Remember It's Just for Fun", pPre: "Whatever the result says, treat it as a lighthearted moment, not a real signal. Real compatibility is built through actual conversations — not a numerology formula.", link: null, pExtra: "No score, high or low, should change how you actually feel about someone or how you choose to act — it's a game, not a verdict." },
    ],
    closingH2: "Making It a Group Activity",
    closingP: "Many of these ideas work best as a shared activity rather than something you try alone. Passing a phone around a group of friends, taking turns entering names, and reacting to each result together tends to be far more fun than running the calculator solo. It also takes the pressure off any one result — when everyone's getting scored, no single percentage feels like it means too much, which is really the spirit these tools were built for in the first place.",
    ctaPre: "Ready to see your score? Head to the",
    ctaLink: "Crush Calculator",
    ctaPost: "and give it a try.",
  },
  hi: {
    title: "आपके क्रश के नाम के साथ करने के लिए 10 मज़ेदार चीज़ें (लव कैलकुलेटर के अलावा)",
    p1Pre: "आपके क्रश का नाम हमारे",
    p1Link: "क्रश कैलकुलेटर",
    p1Post: "में डालना एक अच्छी शुरुआत है, लेकिन अगर आप समय बिताने के और हल्के-फुल्के तरीके ढूंढ रहे हैं, तो यहां दस और मज़ेदार आइडिया हैं।",
    items: [
      { h: "1. FLAMES गेम आज़माएं", pPre: "प्रतिशत की बजाय, एक कैटेगरी पाएं — फ्रेंड्स, लवर्स, अफेक्शनेट, मैरिज, एनिमीज़, या सिबलिंग्स — हमारे", link: "FLAMES कैलकुलेटर", href: "/tools/flames-calculator", pPost: "के साथ।" },
      { h: "2. सोलमेट-स्टाइल स्कोर जांचें", pPre: "एक गहरे कनेक्शन के बारे में जिज्ञासु हैं? हमारा", link: "सोलमेट कैलकुलेटर", href: "/tools/soulmate-calculator", pPost: "वही गणना ज़्यादा रोमांटिक अंदाज़ में इस्तेमाल करता है।" },
      { h: "3. दोस्तों के साथ परिणाम की तुलना करें", pPre: "अपने क्रश का नाम अपने दोस्तों के नामों के साथ भी आज़माएं — सिर्फ मज़े के लिए, और देखें किसका स्कोर सबसे ऊंचा है।", link: null },
      { h: "4. देखें मैरिज कम्पैटिबिलिटी क्या कहती है", pPre: "सीधे लंबे समय की काल्पनिक स्थिति पर जाएं हमारे", link: "मैरिज कम्पैटिबिलिटी कैलकुलेटर", href: "/tools/marriage-compatibility", pPost: "के साथ — बिल्कुल मज़े के लिए।" },
      { h: "5. इसके पीछे की न्यूमेरोलॉजी जानें", pPre: "जानना चाहते हैं नंबर असल में कैसे काम करते हैं? हमारी", link: "न्यूमेरोलॉजी गाइड", href: "/blog/what-is-numerology", pPost: "इसे आसानी से समझाती है।" },
      { h: "6. जन्मदिन जोड़कर देखें", pPre: "हमारे ज़्यादातर कैलकुलेटर आपको दोनों जन्म तिथियां जोड़ने की सुविधा देते हैं — देखें परिणाम कितना बदलता है।", link: null },
      { h: "7. WhatsApp पर परिणाम शेयर करें", pPre: "हर परिणाम के साथ एक-टैप WhatsApp शेयर बटन आता है, ताकि आप अपना स्कोर किसी दोस्त (या हिम्मत हो तो अपने क्रश) को भेज सकें।", link: null },
      { h: "8. परिणाम डाउनलोड करके सेव करें", pPre: "कॉपी रखना चाहते हैं? हर परिणाम को एक इमेज के रूप में डाउनलोड किया जा सकता है।", link: null },
      { h: "9. निकनेम के साथ दोबारा आज़माएं", pPre: "पूरे नाम की बजाय निकनेम के साथ गणना दोबारा आज़माएं — क्योंकि फॉर्मूला अक्षर-आधारित है, छोटे बदलाव भी स्कोर बदल सकते हैं।", link: null },
      { h: "10. याद रखें यह सिर्फ मज़े के लिए है", pPre: "परिणाम जो भी कहे, इसे एक हल्के-फुल्के पल की तरह लें, असली संकेत की तरह नहीं। असली कम्पैटिबिलिटी असली बातचीत से बनती है — किसी न्यूमेरोलॉजी फॉर्मूले से नहीं।", link: null },
    ],
    ctaPre: "अपना स्कोर देखने के लिए तैयार हैं? जाएं",
    ctaLink: "क्रश कैलकुलेटर",
    ctaPost: "पर और आज़माएं।",
  },
};
