export const numerologyBlogContent = {
  en: {
    title: "What Is Numerology? A Simple Guide for Beginners",
    p1Pre: "If you've ever used a",
    p1Link: "love calculator by name",
    p1Post: "and wondered how it turns two names into a percentage, the answer usually traces back to numerology. It's a concept that shows up in everything from name generators to birthday readings, so it's worth understanding in plain terms.",
    h2_1: "The Basic Idea Behind Numerology",
    p2: "Numerology is a belief system that assigns meaning to numbers, often by converting letters or dates into numeric values. The core idea is that numbers carry symbolic weight, and that patterns in those numbers can say something about a person, a name, or an event.",
    h2_2: "How Letters Become Numbers",
    p3: "One of the most common systems assigns each letter of the alphabet a number from 1 to 9, repeating the sequence for later letters. Once every letter in a name has a number, those numbers get added together and reduced down to a single digit — a process called digit reduction.",
    p4: "For example, imagine a name whose letters add up to 47. To reduce that, you'd add 4 + 7 to get 11, then reduce again by adding 1 + 1 to land on 2. That final single digit is treated as the name's \"numerology number.\"",
    h2_3: "How This Connects to Love Calculators",
    p5Pre: "A typical",
    p5Link: "name love calculator",
    p5Post: "takes this same letter-to-number process, applies it to two names separately, and then combines the two results using its own formula to produce a compatibility percentage. Some tools, including ours, also let you add a date of birth.",
    h2_4: "Is Numerology Scientifically Proven?",
    p6: "No. Numerology is a belief-based, divinatory practice, not a scientifically validated field. There's no peer-reviewed evidence that converting letters into numbers reveals anything meaningful about compatibility. That doesn't make it any less fun — it just means it should be treated as entertainment rather than fact.",
    h2_5: "Why We're Upfront About This",
    p7Pre: "We think tools built around numerology — like our",
    p7Link1: "Soulmate Calculator",
    p7Mid: "or",
    p7Link2: "FLAMES Calculator",
    p7Post: "— are most enjoyable when people understand exactly what they are: a fun, numbers-based game, not a scientific test.",
    ctaPre: "Ready to try it yourself? Head back to the",
    ctaLink: "main Love Calculator",
    ctaPost: "and see what your name adds up to.",
  },
  hi: {
    title: "न्यूमेरोलॉजी क्या है? शुरुआती लोगों के लिए एक आसान गाइड",
    p1Pre: "अगर आपने कभी",
    p1Link: "लव कैलकुलेटर बाय नेम",
    p1Post: "इस्तेमाल किया है और सोचा है कि यह दो नामों को प्रतिशत में कैसे बदलता है, तो इसका जवाब आमतौर पर न्यूमेरोलॉजी में मिलता है। यह एक ऐसा कॉन्सेप्ट है जो नेम जनरेटर से लेकर बर्थडे रीडिंग तक हर जगह दिखता है।",
    h2_1: "न्यूमेरोलॉजी के पीछे की मूल सोच",
    p2: "न्यूमेरोलॉजी एक विश्वास प्रणाली है जो नंबरों को अर्थ देती है, अक्सर अक्षरों या तारीखों को नंबरों में बदलकर। मूल विचार यह है कि नंबरों में एक प्रतीकात्मक महत्व होता है, और उन नंबरों के पैटर्न किसी व्यक्ति, नाम या घटना के बारे में कुछ बता सकते हैं।",
    h2_2: "अक्षर नंबर कैसे बनते हैं",
    p3: "सबसे आम प्रणालियों में से एक हर अक्षर को 1 से 9 तक एक नंबर देती है, और आगे के अक्षरों के लिए यह क्रम दोहराया जाता है। एक बार जब नाम के हर अक्षर को नंबर मिल जाता है, उन्हें जोड़ा जाता है और एक अंक तक घटाया जाता है।",
    p4: "उदाहरण के लिए, मान लीजिए किसी नाम के अक्षर जुड़कर 47 बनते हैं। इसे घटाने के लिए, 4 + 7 = 11, फिर 1 + 1 = 2 करके अंतिम अंक निकाला जाता है। यही अंतिम अंक नाम का \"न्यूमेरोलॉजी नंबर\" माना जाता है।",
    h2_3: "यह लव कैलकुलेटर से कैसे जुड़ता है",
    p5Pre: "एक सामान्य",
    p5Link: "नेम लव कैलकुलेटर",
    p5Post: "यही अक्षर-से-नंबर प्रक्रिया इस्तेमाल करता है, इसे दोनों नामों पर अलग-अलग लागू करता है, फिर अपने फॉर्मूले से दोनों परिणामों को मिलाकर एक कम्पैटिबिलिटी प्रतिशत बनाता है।",
    h2_4: "क्या न्यूमेरोलॉजी वैज्ञानिक रूप से सिद्ध है?",
    p6: "नहीं। न्यूमेरोलॉजी एक विश्वास-आधारित प्रणाली है, कोई वैज्ञानिक रूप से मान्य क्षेत्र नहीं। इसका मतलब यह नहीं कि यह कम मज़ेदार है — बस इसे तथ्य की बजाय मनोरंजन के रूप में देखा जाना चाहिए।",
    h2_5: "हम इस बारे में स्पष्ट क्यों हैं",
    p7Pre: "हमारा मानना है कि न्यूमेरोलॉजी पर आधारित टूल — जैसे हमारा",
    p7Link1: "सोलमेट कैलकुलेटर",
    p7Mid: "या",
    p7Link2: "FLAMES कैलकुलेटर",
    p7Post: "— सबसे ज़्यादा मज़ेदार तब होते हैं जब लोग समझते हैं कि ये असल में क्या हैं: एक मज़ेदार, नंबर-आधारित खेल, कोई वैज्ञानिक टेस्ट नहीं।",
    ctaPre: "खुद आज़माना चाहते हैं? वापस",
    ctaLink: "मुख्य लव कैलकुलेटर",
    ctaPost: "पर जाएं और देखें आपका नाम क्या बताता है।",
  },
};

export const compatibilityBlogContent = {
  en: {
    title: "Love Calculator vs Real Compatibility: What's the Difference?",
    p1Pre: "It's easy to type two names into a",
    p1Link: "love calculator by name",
    p1Post: ", get a percentage, and wonder how seriously to take it. The honest answer: not very seriously, and that's actually part of the appeal.",
    h2_1: "What a Love Calculator Actually Measures",
    p2: "A love calculator measures exactly one thing: how two names combine under a numerology-style formula. It doesn't know anything about how two people communicate, handle conflict, or treat each other day to day.",
    h2_2: "What Real Compatibility Actually Depends On",
    p3: "Real compatibility is built from dozens of small, ongoing factors that no calculator can see:",
    list: [
      "How well you communicate, especially during disagreements",
      "Whether your core values and life goals line up",
      "How you each handle stress, and how you support each other",
      "Trust, honesty, and consistency over time",
      "Shared humor, curiosity, and everyday compatibility",
    ],
    p4: "None of these can be reduced to a percentage, and none show up in a name-based calculation.",
    h2_3: "So Why Do People Still Enjoy Love Calculators?",
    p5Pre: "Because they're fun, fast, and low-stakes. Nobody sits down at a",
    p5Link: "Crush Calculator",
    p5Post: "expecting a scientific verdict — it's more like a fortune cookie than a diagnosis.",
    h2_4: "A Simple Rule of Thumb",
    p6: "Enjoy the score, share it if it's fun, and then let real conversations — not a number — guide anything that actually matters in your relationship.",
    ctaPre: "Want to try a different angle on the same names? Check out our",
    ctaLink1: "FLAMES Calculator",
    ctaMid: "or head back to the",
    ctaLink2: "main Love Calculator",
    ctaPost: ".",
  },
  hi: {
    title: "लव कैलकुलेटर बनाम असली कम्पैटिबिलिटी: क्या फर्क है?",
    p1Pre: "किसी",
    p1Link: "लव कैलकुलेटर बाय नेम",
    p1Post: "में दो नाम डालना, एक प्रतिशत पाना, और सोचना कि इसे कितनी गंभीरता से लें आसान है। ईमानदार जवाब: ज़्यादा गंभीरता से नहीं, और यही इसकी खासियत भी है।",
    h2_1: "लव कैलकुलेटर असल में क्या मापता है",
    p2: "लव कैलकुलेटर सिर्फ एक चीज़ मापता है: दो नाम न्यूमेरोलॉजी फॉर्मूले के तहत कैसे मिलते हैं। इसे यह नहीं पता कि दो लोग कैसे बातचीत करते हैं या एक-दूसरे के साथ कैसा व्यवहार करते हैं।",
    h2_2: "असली कम्पैटिबिलिटी असल में किस पर निर्भर करती है",
    p3: "असली कम्पैटिबिलिटी दर्जनों छोटे, लगातार चलने वाले कारकों से बनती है जिन्हें कोई कैलकुलेटर नहीं देख सकता:",
    list: [
      "आप कितनी अच्छी तरह बातचीत करते हैं, खासकर असहमति में",
      "क्या आपके मूल मूल्य और जीवन लक्ष्य मेल खाते हैं",
      "आप तनाव कैसे संभालते हैं और एक-दूसरे को कैसे सहारा देते हैं",
      "समय के साथ भरोसा, ईमानदारी और निरंतरता",
      "साझा हास्य, जिज्ञासा, और रोज़मर्रा की कम्पैटिबिलिटी",
    ],
    p4: "इनमें से कुछ भी प्रतिशत में नहीं बदला जा सकता, और न ही किसी नाम-आधारित गणना में दिखता है।",
    h2_3: "फिर भी लोग लव कैलकुलेटर क्यों पसंद करते हैं?",
    p5Pre: "क्योंकि ये मज़ेदार, तेज़ और बिना किसी जोखिम के हैं। कोई भी",
    p5Link: "क्रश कैलकुलेटर",
    p5Post: "से वैज्ञानिक फैसले की उम्मीद नहीं रखता — यह किसी डायग्नोसिस से ज़्यादा फॉर्च्यून कुकी जैसा है।",
    h2_4: "एक आसान नियम",
    p6: "स्कोर को एन्जॉय करें, अगर मज़ेदार लगे तो शेयर करें, और फिर असली बातचीत को ही अपने रिश्ते की असली बातों का मार्गदर्शक बनने दें, किसी नंबर को नहीं।",
    ctaPre: "उन्हीं नामों पर कुछ अलग आज़माना चाहते हैं? हमारा",
    ctaLink1: "FLAMES कैलकुलेटर",
    ctaMid: "देखें या वापस",
    ctaLink2: "मुख्य लव कैलकुलेटर",
    ctaPost: "पर जाएं।",
  },
};

export const flamesHistoryBlogContent = {
  en: {
    title: "The History of the FLAMES Game — Where Did It Come From?",
    p1Pre: "Long before anyone typed two names into an online",
    p1Link: "FLAMES Calculator",
    p1Post: ", the game was played the old-fashioned way — with a pen, paper, and a bit of patience.",
    h2_1: "A Playground Classic",
    p2: "FLAMES — short for Friends, Lovers, Affectionate, Marriage, Enemies, Siblings — traditionally spread as a schoolyard game. Two people would write out their names, cross out matching letters by hand, count what was left, and count through the letters F-L-A-M-E-S until one remained.",
    h2_2: "Why It Became So Popular",
    p3: "Part of the appeal was how quick and visual it was. Unlike a full percentage-based love calculator, FLAMES gave a single, easy-to-remember word as an answer. It also worked for more than just crushes.",
    h2_3: "From Paper to Pixels",
    p4Pre: "As online tools became common, FLAMES was one of the first \"love games\" to be digitized. Today's",
    p4Link: "FLAMES Calculator",
    p4Post: "runs the exact same letter-cancelling, letter-counting process instantly, without needing a pen or paper.",
    h2_4: "Is FLAMES Still Just for Fun?",
    p5: "Yes, and that hasn't changed. FLAMES has never been a scientifically validated relationship test — it's always been a lighthearted game, whether played on a napkin in the 90s or on a phone today.",
    ctaPre: "Curious what your names spell out? Try the",
    ctaLink1: "FLAMES Calculator",
    ctaMid: "or compare it with a percentage-based result on our",
    ctaLink2: "main Love Calculator",
    ctaPost: ".",
  },
  hi: {
    title: "FLAMES गेम का इतिहास — यह कहां से आया?",
    p1Pre: "किसी के भी ऑनलाइन",
    p1Link: "FLAMES कैलकुलेटर",
    p1Post: "में दो नाम डालने से बहुत पहले, यह खेल पुराने तरीके से खेला जाता था — पेन, पेपर और थोड़े धैर्य के साथ।",
    h2_1: "एक स्कूल का क्लासिक खेल",
    p2: "FLAMES — फ्रेंड्स, लवर्स, अफेक्शनेट, मैरिज, एनिमीज़, सिबलिंग्स का संक्षिप्त रूप — पारंपरिक रूप से एक स्कूली खेल की तरह फैला। दो लोग अपने नाम लिखते, मिलते-जुलते अक्षरों को हाथ से काटते, बचे हुए को गिनते, और F-L-A-M-E-S में गिनती करते जब तक एक अक्षर न बचे।",
    h2_2: "यह इतना लोकप्रिय क्यों हुआ",
    p3: "इसकी खासियत यह थी कि यह कितना तेज़ और विज़ुअल था। पूरे प्रतिशत-आधारित लव कैलकुलेटर के उलट, FLAMES एक आसानी से याद रहने वाला शब्द जवाब देता था।",
    h2_3: "पेपर से पिक्सल तक",
    p4Pre: "जैसे-जैसे ऑनलाइन टूल आम हुए, FLAMES डिजिटल होने वाले पहले \"लव गेम्स\" में से एक था। आज का",
    p4Link: "FLAMES कैलकुलेटर",
    p4Post: "वही अक्षर-काटने, अक्षर-गिनने की प्रक्रिया तुरंत करता है, बिना पेन-पेपर के।",
    h2_4: "क्या FLAMES अभी भी सिर्फ मज़े के लिए है?",
    p5: "हाँ, और यह नहीं बदला। FLAMES कभी भी वैज्ञानिक रूप से प्रमाणित रिश्ता परीक्षण नहीं रहा — यह हमेशा से एक हल्का-फुल्का खेल रहा है, चाहे 90 के दशक में नैपकिन पर खेला गया हो या आज फोन पर।",
    ctaPre: "जानना चाहते हैं आपके नाम क्या बताते हैं? आज़माएं",
    ctaLink1: "FLAMES कैलकुलेटर",
    ctaMid: "या हमारे",
    ctaLink2: "मुख्य लव कैलकुलेटर",
    ctaPost: "पर प्रतिशत-आधारित परिणाम से तुलना करें।",
  },
};

export const funThingsBlogContent = {
  en: {
    title: "10 Fun Things to Do With Your Crush's Name (Besides a Love Calculator)",
    p1Pre: "Running your crush's name through our",
    p1Link: "Crush Calculator",
    p1Post: "is a great start, but if you're looking for more lighthearted ways to pass the time, here are ten more fun, low-pressure ideas.",
    items: [
      { h: "1. Try the FLAMES Game", pPre: "Instead of a percentage, get a category — Friends, Lovers, Affectionate, Marriage, Enemies, or Siblings — with our", link: "FLAMES Calculator", href: "/tools/flames-calculator", pPost: "." },
      { h: "2. Check a Soulmate-Style Score", pPre: "Curious about a deeper connection angle? The", link: "Soulmate Calculator", href: "/tools/soulmate-calculator", pPost: "uses the same math with a more romantic framing." },
      { h: "3. Compare Results With Friends", pPre: "Run the same crush's name against your friends' names too — just for laughs, and to compare who \"wins\" the highest score.", link: null },
      { h: "4. See What Marriage Compatibility Says", pPre: "Jump straight to the long-term hypothetical with our", link: "Marriage Compatibility Calculator", href: "/tools/marriage-compatibility", pPost: "— purely for fun, of course." },
      { h: "5. Learn the Numerology Behind It", pPre: "If you're curious how the numbers actually work, our", link: "numerology guide", href: "/blog/what-is-numerology", pPost: "breaks it down simply." },
      { h: "6. Try Adding a Birthday", pPre: "Most of our calculators let you optionally add both dates of birth for an extra numerology layer — see how much the result shifts.", link: null },
      { h: "7. Share the Result on WhatsApp", pPre: "Every result comes with a one-tap WhatsApp share button, so you can send your score to a friend (or even your crush, if you're feeling bold).", link: null },
      { h: "8. Download and Save the Result", pPre: "Want to keep a copy? Every result can be downloaded as an image to save or share elsewhere.", link: null },
      { h: "9. Run It Again With a Nickname", pPre: "Try the calculation again using a nickname instead of a full name — since the formula is letter-based, even small changes can shift the score.", link: null },
      { h: "10. Remember It's Just for Fun", pPre: "Whatever the result says, treat it as a lighthearted moment, not a real signal. Real compatibility is built through actual conversations — not a numerology formula.", link: null },
    ],
    ctaPre: "Ready to see your score? Head to the",
    ctaLink: "Crush Calculator",
    ctaPost: "and give it a try.",
  },
  hi: {
    title: "आपके क्रश के नाम के साथ करने के लिए 10 मज़ेदार चीज़ें (लव कैलकुलेटर के अलावा)",
    p1Pre: "आपके क्रश का नाम हमारे",
    p1Link: "क्रश कैलकुलेटर",
    p1Post: "में डालना एक अच्छी शुरुआत है, लेकिन अगर आप समय बिताने के और हल्के-फुल्के तरीके ढूंढ रहे हैं, तो यहां दस और मज़ेदार आइडिया हैं।",
    items: [
      { h: "1. FLAMES गेम आज़माएं", pPre: "प्रतिशत की बजाय, एक कैटेगरी पाएं — फ्रेंड्स, लवर्स, अफेक्शनेट, मैरिज, एनिमीज़, या सिबलिंग्स — हमारे", link: "FLAMES कैलकुलेटर", href: "/tools/flames-calculator", pPost: "के साथ।" },
      { h: "2. सोलमेट-स्टाइल स्कोर जांचें", pPre: "एक गहरे कनेक्शन के बारे में जिज्ञासु हैं? हमारा", link: "सोलमेट कैलकुलेटर", href: "/tools/soulmate-calculator", pPost: "वही गणना ज़्यादा रोमांटिक अंदाज़ में इस्तेमाल करता है।" },
      { h: "3. दोस्तों के साथ परिणाम की तुलना करें", pPre: "अपने क्रश का नाम अपने दोस्तों के नामों के साथ भी आज़माएं — सिर्फ मज़े के लिए, और देखें किसका स्कोर सबसे ऊंचा है।", link: null },
      { h: "4. देखें मैरिज कम्पैटिबिलिटी क्या कहती है", pPre: "सीधे लंबे समय की काल्पनिक स्थिति पर जाएं हमारे", link: "मैरिज कम्पैटिबिलिटी कैलकुलेटर", href: "/tools/marriage-compatibility", pPost: "के साथ — बिल्कुल मज़े के लिए।" },
      { h: "5. इसके पीछे की न्यूमेरोलॉजी जानें", pPre: "जानना चाहते हैं नंबर असल में कैसे काम करते हैं? हमारी", link: "न्यूमेरोलॉजी गाइड", href: "/blog/what-is-numerology", pPost: "इसे आसानी से समझाती है।" },
      { h: "6. जन्मदिन जोड़कर देखें", pPre: "हमारे ज़्यादातर कैलकुलेटर आपको दोनों जन्म तिथियां जोड़ने की सुविधा देते हैं — देखें परिणाम कितना बदलता है।", link: null },
      { h: "7. WhatsApp पर परिणाम शेयर करें", pPre: "हर परिणाम के साथ एक-टैप WhatsApp शेयर बटन आता है, ताकि आप अपना स्कोर किसी दोस्त (या हिम्मत हो तो अपने क्रश) को भेज सकें।", link: null },
      { h: "8. परिणाम डाउनलोड करके सेव करें", pPre: "कॉपी रखना चाहते हैं? हर परिणाम को एक इमेज के रूप में डाउनलोड किया जा सकता है।", link: null },
      { h: "9. निकनेम के साथ दोबारा आज़माएं", pPre: "पूरे नाम की बजाय निकनेम के साथ गणना दोबारा आज़माएं — क्योंकि फॉर्मूला अक्षर-आधारित है, छोटे बदलाव भी स्कोर बदल सकते हैं।", link: null },
      { h: "10. याद रखें यह सिर्फ मज़े के लिए है", pPre: "परिणाम जो भी कहे, इसे एक हल्के-फुल्के पल की तरह लें, असली संकेत की तरह नहीं। असली कम्पैटिबिलिटी असली बातचीत से बनती है — किसी न्यूमेरोलॉजी फॉर्मूले से नहीं।", link: null },
    ],
    ctaPre: "अपना स्कोर देखने के लिए तैयार हैं? जाएं",
    ctaLink: "क्रश कैलकुलेटर",
    ctaPost: "पर और आज़माएं।",
  },
};
