export const homeContent = {
  en: {
    h1: "Love Calculator by Name – Check Your Love Compatibility Percentage",
    tagline:
      "Enter two names to calculate a fun love compatibility percentage. You can also add dates of birth for a name-and-DOB based result.",
    trustLine:
      "A simple, private, and free love calculator designed for entertainment and compatibility exploration.",
    calculateBtn: "Calculate Love %",
    name1Label: "Name 1",
    name2Label: "Name 2",

    // 2. What Is a Love Calculator by Name?
    section2Title: "What Is a Love Calculator by Name?",
    section2p1:
      "A love calculator by name is an online tool that generates a compatibility percentage using the names entered by two people. It's one of the simplest ways to run a true love calculator by name check without filling out a long questionnaire — you just type in two names and get an instant, shareable score.",
    section2p2:
      "Some calculators, including this one, also let you add a date of birth to layer in an additional numerology-style interpretation, which is why you'll often see this described as a love calculator by name and date of birth rather than a plain name-only tool.",
    section2p3:
      "The result you receive is meant for entertainment. It is not a scientific measurement of a real relationship, and it should never replace honest conversation, trust, or time spent getting to know someone. Think of it as a playful icebreaker — a real love calculator that people use for fun with a crush, partner, or friend, rather than a serious predictor of the future. My love calculator by name works the same way every time: same two names in, same score out, no hidden variables.",

    // 3. What Does Your Love Calculator Score Mean?
    section3Title: "What Does Your Love Calculator Score Mean?",
    scoreTableHeaders: ["Score Range", "What It Suggests"],
    scoreRows: [
      ["90% – 99%", "Exceptional Match — strong playful chemistry"],
      ["75% – 89%", "Strong Connection — good fun-scale potential"],
      ["55% – 74%", "Promising Match — a fair, balanced result"],
      ["40% – 54%", "Mixed Signals — a moderate, in-between score"],
      ["Below 40%", "Room to Grow — a lower score on this fun scale"],
    ],
    section3p1:
      "These ranges exist purely to make the result easier to read at a glance, and they're the same scale used across every love calculator by name percentage test on this site — the Love Calculator, Soulmate Calculator, Marriage Compatibility Calculator, and Friendship Calculator all interpret their scores this way.",
    section3p2:
      "A 95% score does not scientifically mean two people are destined to be together, and a lower score does not mean the opposite. This is deliberate: we never claim a real love calculator can prove soulmate status. Real compatibility depends on communication, shared values, and effort — not a single number generated by a name love calculator.",

    // 4. How Does the Love Calculator by Name Work?
    section4Title: "How Does the Love Calculator by Name Work?",
    section4p1:
      "Our calculator uses a numerology-style approach, one of the most common methods behind any name love calculator online. It doesn't pull from a relationship database, social media, or personal history — it purely transforms the letters in each name into numbers, then combines those numbers using a set formula to produce a percentage between 30% and 99%.",
    section4h3a: "Does the Love Calculator Use Numerology?",
    section4p2:
      "Yes. Numerology assigns a numeric value to each letter of the alphabet, usually cycling from 1 through 9. When you type in two names, the calculator converts every letter into its number, adds those values together for each name, and reduces the result down to a single digit following a consistent, repeatable formula.",
    section4h3b: "How Are Names Converted Into Numbers?",
    section4p3:
      "In a numerology-style calculation, letters can be assigned numerical values and reduced to smaller numbers. Those values can then be combined according to the calculator's formula to produce a compatibility result. For instance, imagine two short names where one reduces to the number 5 and the other to the number 7 — the calculator combines 5 and 7 using its internal formula to land on a final percentage. This formula is not scientifically proven — it's a long-standing entertainment tradition rather than a validated method, and we're upfront about that throughout this page.",
    section4h3c: "Does Date of Birth Change the Result?",
    section4p4:
      "If you choose to add both dates of birth, the calculator layers in an extra numerology-style calculation based on those numbers, which is what makes this a genuine love calculator by name and date of birth free tool rather than a names-only version. This can shift your final score slightly, giving a result that feels more personalized. Leaving the date of birth fields blank still gives you a complete, name-only result — it's entirely optional, and neither version is more \"correct\" than the other.",
    section4p5Pre:
      "Curious about the numbers behind numerology? Read more in our",
    section4p5Link: "guide to numerology",
    section4p5Mid: "or jump straight into the",
    section4p5Link2: "Soulmate Calculator",
    section4p5Post: "to see the same formula framed around a deeper connection.",

    // 5. Love Calculator by Name and Date of Birth
    section5Title: "Can You Calculate Love Compatibility by Name and Date of Birth?",
    section5p1:
      "Yes — our tool supports a full love calculator by name and date of birth experience for anyone who wants a deeper, more personalized-feeling result, alongside the simpler name-only option for people who just want a quick answer. Here's exactly how it works, step by step:",
    section5Steps: [
      "Enter the first person's name.",
      "Enter the second person's name.",
      "Add both dates of birth (optional).",
      "Select a relationship type — Crush, Couple, Best Friends, Sister/Brother, or Other.",
      "Click Calculate.",
      "View your compatibility result instantly, with a Try Again option to run it again.",
    ],
    section5p2:
      "The core difference between a name-only calculation and a name-plus-DOB calculation is depth. A name-only result relies purely on the letters in each name — fast, simple, and perfect if you just want a quick love calculator by name and date check. Adding a date of birth introduces a second numerology layer, which can shift the score and add another angle to the fun interpretation.",
    section5p3:
      "Neither version is hidden behind a paywall or signup form. Whether you search for a love calculator by name and date of birth free option or just want to test two names quickly, this same tool on this same page covers both use cases without switching pages.",

    // 6. Love Calculator vs Compatibility Test
    section6Title: "What Is the Difference Between a Love Calculator and a Compatibility Test?",
    section6p1:
      "Although the two are often searched together, a love calculator and a compatibility test serve genuinely different purposes, and it's worth understanding the difference before you take either result too seriously.",
    comparisonTableTitle: "Love Calculator vs Compatibility Test",
    comparisonTableHeaders: ["Love Calculator", "Compatibility Test"],
    comparisonTableRows: [
      ["Usually produces a single percentage.", "Usually produces a broader written assessment."],
      ["Often uses just two names (with or without DOB).", "Can consider personality traits, values, and interests."],
      ["Designed for a quick, fun result.", "Usually takes longer and goes deeper."],
      ["Best for a light, shareable moment.", "Better for genuine self-reflection about a relationship."],
      ["No scientific validation claimed.", "Some versions are based on psychological research."],
    ],
    section6h3: "Is a Love Calculator Scientifically Accurate?",
    section6p2:
      "No. A name-based love percentage is not a scientifically validated measurement of romantic compatibility. It is best treated as an entertainment or numerology-style result — fun to explore, and fun to compare with friends, but not something to base real relationship decisions on. If you want something closer to genuine self-reflection, a proper compatibility test that asks about values, communication style, and goals will always tell you more than any love calculator by name percentage ever could.",

    // 7. How Does Numerology Calculate Love Compatibility?
    section7Title: "How Does Numerology Calculate Love Compatibility by Name?",
    section7p1:
      "If you want to understand the mechanics behind a real love calculator rather than just trusting a black box, it helps to break the process into four simple steps.",
    section7h3a: "Step 1 — Assign Values to Letters",
    section7p2:
      "Numerology assigns each letter of the alphabet a number, usually from 1 to 9, with the pattern repeating for later letters (so J behaves like A, K like B, and so on). This creates a consistent numeric fingerprint for any given name, no matter how long or short it is.",
    section7h3b: "Step 2 — Calculate Each Name",
    section7p3:
      "Every letter's value in a name is added together. For a simple fictional example, imagine a name where the letters add up to 23 — that number then gets reduced down to a single digit by adding its own digits together (2 + 3 = 5). This single-digit number becomes that name's core numerology value.",
    section7h3c: "Step 3 — Combine the Results",
    section7p4:
      "Once each name has its own reduced number, the calculator combines both numbers using a formula to produce the final compatibility score, typically expressed as a percentage between 30% and 99%. Our formula is symmetrical by design, so it treats both people's names as equally important inputs.",
    section7h3d: "Step 4 — Is Numerology a Scientific Method?",
    section7p5:
      "No. Numerology is a belief-based, divinatory system rather than a scientifically established method for predicting relationship outcomes. We explain this openly because we'd rather you trust the tool for what it actually is — a fun, honest, entertainment experience — than oversell it as something it isn't. This honesty is also why you'll see the same disclaimer repeated under every result on this site.",

    // 8. Does the Order of Names Matter?
    section8Title: "Does the Order of Names Matter in a Love Calculator?",
    section8p1:
      "No. Our formula is symmetrical, which means the order of the two names does not change the percentage — the same two inputs are used in the calculation regardless of which name you type first. Whether you enter yourself first or your crush first, the result stays exactly the same.",
    section8p2:
      "This is a common question because some online tools are built asymmetrically, where Name 1 and Name 2 are treated differently, producing a different score depending on order. We've deliberately avoided that here, since it can feel confusing or even unfair when a fun tool gives two different answers for the exact same pair of people.",

    // 9. Is My Data Private?
    section9Title: "Is My Name and Date of Birth Safe to Enter?",
    section9p1:
      "Your information should only be used for the calculator's stated purpose — generating a fun compatibility result. We recommend avoiding highly sensitive personal information in any online tool, and checking a website's",
    section9p1LinkText: "privacy policy",
    section9p1Post:
      "to understand whether submitted data is stored or shared before you enter anything.",
    section9p2:
      "On this site, the core name and date-of-birth calculation runs directly in your browser and does not need to be sent to a server to produce your score. Separately, if you see an AI-generated personalized note appear alongside your result, the names and score are sent securely to our server so that note can be generated — this part is optional to the core calculation, is not required for the calculator to work, and never stores your data permanently.",
    section9p3: "See our",
    section9p3LinkText: "Privacy Policy",
    section9p3Post:
      "for full details on what is and isn't collected, and how our advertising and analytics partners may use cookies.",

    // 10. Marriage Compatibility by Name
    section10Title: "Can a Love Calculator Check Marriage Compatibility by Name?",
    section10p1: "A name-based calculator, like our",
    section10Link: "Marriage Compatibility Calculator",
    section10p1Post:
      ", can generate a numerology-style compatibility result for two names, which is exactly what people mean when they search for marriage compatibility by name or love compatibility by name in a longer-term context. What it cannot do is reliably predict whether an actual marriage will succeed. That depends on real-world factors far beyond any online formula, including:",
    section10List: [
      "Communication",
      "Trust",
      "Shared values",
      "Financial expectations",
      "Family expectations",
      "Emotional compatibility",
      "Long-term goals",
    ],
    section10p2:
      "Treat any marriage compatibility by name result as a fun conversation starter, not a replacement for these deeper, real-life factors. If two names score low, that says nothing about a real couple's actual chances — and if two names score 99%, that's not a substitute for the conversations engaged and married couples need to have about money, family, and the future.",

    // 11. Love Calculator vs FLAMES
    section11Title: "What Is the Difference Between a Love Calculator and FLAMES?",
    section11p1:
      "This comparison comes up constantly, because a love calculator by name FLAMES search usually means someone wants to know which of the two tools they should try first. The honest answer is: they're both fun, they just present results differently.",
    flamesTableHeaders: ["Tool", "What You Get"],
    flamesTableRows: [
      ["Love Calculator", "A single compatibility percentage (e.g. 82%)."],
      ["FLAMES Calculator", "One of six relationship categories: Friends, Lovers, Affectionate, Marriage, Enemies, or Siblings."],
    ],
    section11p2Pre:
      "If you'd like to try a FLAMES-style calculation instead of, or alongside, a percentage, use our",
    section11p2Link: "FLAMES Calculator",
    section11p2Post:
      "— many people run both tools back to back with the same two names, just to compare a flames love calculator percentage-style feel against a category-based result.",

    exploreTitle: "Explore More Love & Relationship Calculators",
    exploreSub: "Every result below is generated the same way — fast, free, and just for fun.",

    // 13. Mobile / App Intent
    section13Title: "Can I Use the Love Calculator on Mobile?",
    section13p1:
      "Yes. This entire site — the calculator, the tool pages, and the blog — is built to work smoothly on phones, tablets, and desktop browsers alike. You don't necessarily need a separate app to use a browser-based love calculator; opening this page on your phone gives you the same experience as a native app, without needing to download anything or grant any permissions.",
    section13p2:
      "This also covers the love calculator by name app search — while we don't currently offer a downloadable app, the mobile web version is built to feel just as fast and responsive, so you can bookmark this page to your home screen and open it the same way you would any app.",

    // 14. Fun Use Cases
    section14Title: "What Can You Use a Love Calculator For?",
    section14p1:
      "People use a name love calculator in all kinds of light-hearted situations — checking a score with a new crush, seeing what a couple's names generate together, comparing results with best friends, or even running a sister love calculator by name or best friend love calculator by name just for a laugh.",
    section14p2:
      "It's a popular pick for Valentine's Day, group chats, and social media sharing, precisely because it takes seconds and never asks for anything serious in return. Some people search for a love calculator by name prank specifically to send a funny result to a sibling or classmate — and because the tool is symmetrical and private, there's no harm in running it as many times as you like, with as many different name pairs as you like.",
    section14p3:
      "Whether you're testing \"i love calculator by name\" out of curiosity for yourself, or sending a result to a friend after a \"love love calculator by name\" search led you here, the goal is the same: a quick, fun moment, not a verdict on real life.",

    faqTitle: "Frequently Asked Questions About Love Calculators",

    ctaTitle: "Ready to Check Your Love Compatibility?",
    ctaP:
      "Enter two names above and discover your fun love compatibility percentage. You can also explore our FLAMES, soulmate, friendship, and other relationship calculators.",
    ctaBtn: "Calculate Love Compatibility →",
  },

  hi: {
    h1: "लव कैलकुलेटर बाय नेम – अपनी लव कम्पैटिबिलिटी प्रतिशत जानें",
    tagline:
      "दो नाम डालें और एक मज़ेदार लव कम्पैटिबिलिटी प्रतिशत निकालें। अधिक सटीक (नाम + जन्म तिथि आधारित) परिणाम के लिए जन्म तिथि भी जोड़ सकते हैं।",
    trustLine:
      "यह एक सरल, प्राइवेट और मुफ़्त लव कैलकुलेटर है, जो मनोरंजन और कम्पैटिबिलिटी एक्सप्लोर करने के लिए बनाया गया है।",
    calculateBtn: "लव % कैलकुलेट करें",
    name1Label: "नाम 1",
    name2Label: "नाम 2",

    section2Title: "लव कैलकुलेटर बाय नेम क्या है?",
    section2p1:
      "लव कैलकुलेटर बाय नेम एक ऑनलाइन टूल है जो दो लोगों के नामों का उपयोग करके एक कम्पैटिबिलिटी प्रतिशत बनाता है। यह बिना किसी लंबे प्रश्नावली को भरे एक असली लव कैलकुलेटर बाय नेम चेक करने का सबसे आसान तरीका है — बस दो नाम डालें और तुरंत एक शेयर करने लायक स्कोर पाएं।",
    section2p2:
      "कुछ कैलकुलेटर, जिनमें यह भी शामिल है, आपको जन्म तिथि जोड़ने की सुविधा भी देते हैं, जिससे एक अतिरिक्त न्यूमेरोलॉजी-शैली की व्याख्या मिलती है — इसीलिए इसे अक्सर लव कैलकुलेटर बाय नेम एंड डेट ऑफ बर्थ कहा जाता है, सिर्फ नाम-आधारित टूल नहीं।",
    section2p3:
      "आपको मिलने वाला परिणाम केवल मनोरंजन के लिए है। यह किसी असली रिश्ते का वैज्ञानिक मापदंड नहीं है, और इसे कभी भी ईमानदार बातचीत, भरोसे, या किसी को जानने में लगने वाले समय की जगह नहीं लेनी चाहिए। इसे एक हल्के-फुल्के आइसब्रेकर की तरह देखें — जिसे लोग किसी क्रश, पार्टनर या दोस्त के साथ मज़े के लिए इस्तेमाल करते हैं। हमारा लव कैलकुलेटर हर बार एक जैसा काम करता है: वही दो नाम डालें, वही स्कोर मिले, कोई छिपा हुआ बदलाव नहीं।",

    section3Title: "आपके लव कैलकुलेटर स्कोर का क्या मतलब है?",
    scoreTableHeaders: ["स्कोर रेंज", "इसका क्या मतलब है"],
    scoreRows: [
      ["90% – 99%", "असाधारण मैच — मज़बूत, मज़ेदार केमिस्ट्री"],
      ["75% – 89%", "मज़बूत कनेक्शन — अच्छी संभावना"],
      ["55% – 74%", "अच्छा मैच — एक संतुलित परिणाम"],
      ["40% – 54%", "मिश्रित संकेत — एक मध्यम स्कोर"],
      ["40% से कम", "अभी सुधार की गुंजाइश — इस मज़ेदार स्केल पर एक कम स्कोर"],
    ],
    section3p1:
      "ये रेंज सिर्फ परिणाम को आसानी से समझने के लिए बनाई गई हैं, और यही स्केल इस साइट के हर कैलकुलेटर — लव, सोलमेट, मैरिज कम्पैटिबिलिटी और फ्रेंडशिप — में इस्तेमाल होता है।",
    section3p2:
      "95% स्कोर का वैज्ञानिक रूप से यह मतलब नहीं है कि दो लोग एक-दूसरे के लिए बने हैं, और कम स्कोर का भी उल्टा मतलब नहीं है। यह जानबूझकर है — हम कभी दावा नहीं करते कि कोई असली कैलकुलेटर सोलमेट होने का सबूत दे सकता है। असली कम्पैटिबिलिटी बातचीत, साझा मूल्यों और मेहनत पर निर्भर करती है — किसी नंबर पर नहीं।",

    section4Title: "लव कैलकुलेटर बाय नेम कैसे काम करता है?",
    section4p1:
      "हमारा कैलकुलेटर एक न्यूमेरोलॉजी-शैली की विधि इस्तेमाल करता है, जो किसी भी ऑनलाइन नेम लव कैलकुलेटर के पीछे सबसे सामान्य तरीकों में से एक है। यह किसी रिलेशनशिप डेटाबेस, सोशल मीडिया या व्यक्तिगत इतिहास से जानकारी नहीं लेता — यह सिर्फ हर नाम के अक्षरों को नंबरों में बदलता है, फिर एक तय फॉर्मूला इस्तेमाल करके 30% से 99% के बीच एक प्रतिशत निकालता है।",
    section4h3a: "क्या लव कैलकुलेटर न्यूमेरोलॉजी का उपयोग करता है?",
    section4p2:
      "हाँ। न्यूमेरोलॉजी हर अक्षर को एक नंबर देती है, आमतौर पर 1 से 9 के बीच दोहराते हुए। जब आप दो नाम लिखते हैं, कैलकुलेटर हर अक्षर को उसके नंबर में बदलता है, हर नाम के लिए उन्हें जोड़ता है, और एक तय फॉर्मूले के अनुसार परिणाम को घटाकर एक अंक तक लाता है।",
    section4h3b: "नामों को नंबरों में कैसे बदला जाता है?",
    section4p3:
      "न्यूमेरोलॉजी-शैली की गणना में, अक्षरों को नंबर दिए जाते हैं और उन्हें छोटे अंकों में घटाया जाता है। उदाहरण के लिए, मान लीजिए दो छोटे नाम हैं जिनमें से एक 5 पर और दूसरा 7 पर घटता है — कैलकुलेटर 5 और 7 को अपने फॉर्मूले से मिलाकर एक अंतिम प्रतिशत निकालता है। यह फॉर्मूला वैज्ञानिक रूप से सिद्ध नहीं है — यह एक पुरानी मनोरंजन परंपरा है, और हम इस पूरे पेज में इस बारे में स्पष्ट हैं।",
    section4h3c: "क्या जन्म तिथि परिणाम बदल देती है?",
    section4p4:
      "यदि आप दोनों की जन्म तिथियां जोड़ते हैं, तो कैलकुलेटर उन नंबरों के आधार पर एक अतिरिक्त न्यूमेरोलॉजी गणना जोड़ता है, जो इसे एक असली लव कैलकुलेटर बाय नेम एंड डेट ऑफ बर्थ फ्री टूल बनाता है, सिर्फ नाम-आधारित वर्ज़न नहीं। जन्म तिथि के फ़ील्ड खाली छोड़ने पर भी आपको एक पूरा, केवल-नाम-आधारित परिणाम मिलता है — यह पूरी तरह वैकल्पिक है, और कोई भी वर्ज़न दूसरे से ज़्यादा \"सही\" नहीं है।",
    section4p5Pre: "न्यूमेरोलॉजी के पीछे के नंबरों के बारे में जानना है? हमारी",
    section4p5Link: "न्यूमेरोलॉजी गाइड",
    section4p5Mid: "पढ़ें या सीधे",
    section4p5Link2: "सोलमेट कैलकुलेटर",
    section4p5Post: "आज़माएं, जहां यही फॉर्मूला एक गहरे कनेक्शन के हिसाब से इस्तेमाल होता है।",

    section5Title: "क्या आप नाम और जन्म तिथि से लव कम्पैटिबिलिटी निकाल सकते हैं?",
    section5p1:
      "हाँ — हमारा टूल नाम और जन्म तिथि दोनों के आधार पर एक गहरे, अधिक व्यक्तिगत महसूस होने वाले परिणाम का पूरा समर्थन करता है, साथ ही सिर्फ नाम वाला सरल विकल्प भी उपलब्ध है। यह ऐसे काम करता है:",
    section5Steps: [
      "पहले व्यक्ति का नाम डालें।",
      "दूसरे व्यक्ति का नाम डालें।",
      "दोनों की जन्म तिथियां जोड़ें (वैकल्पिक)।",
      "रिलेशनशिप टाइप चुनें — क्रश, कपल, बेस्ट फ्रेंड्स, सिस्टर/ब्रदर, या अन्य।",
      "कैलकुलेट पर क्लिक करें।",
      "तुरंत अपना परिणाम देखें, और चाहें तो फिर से आज़माएं।",
    ],
    section5p2:
      "केवल-नाम आधारित गणना और नाम+जन्म तिथि आधारित गणना के बीच मुख्य अंतर गहराई का है। केवल-नाम परिणाम सिर्फ नाम के अक्षरों पर निर्भर करता है — तेज़ और सरल। जन्म तिथि जोड़ने से एक दूसरी न्यूमेरोलॉजी परत जुड़ जाती है, जो स्कोर को थोड़ा बदल सकती है।",
    section5p3:
      "दोनों वर्ज़न बिना किसी साइनअप या पेवॉल के उपलब्ध हैं। चाहे आप नाम और जन्म तिथि वाला मुफ़्त विकल्प चाहें या बस दो नाम जल्दी टेस्ट करना चाहें, यही टूल इसी पेज पर दोनों काम करता है।",

    section6Title: "लव कैलकुलेटर और कम्पैटिबिलिटी टेस्ट में क्या अंतर है?",
    section6p1: "हालांकि दोनों को अक्सर साथ खोजा जाता है, इनके उद्देश्य वाकई अलग-अलग हैं, और परिणाम को गंभीरता से लेने से पहले यह अंतर समझना ज़रूरी है।",
    comparisonTableTitle: "लव कैलकुलेटर बनाम कम्पैटिबिलिटी टेस्ट",
    comparisonTableHeaders: ["लव कैलकुलेटर", "कम्पैटिबिलिटी टेस्ट"],
    comparisonTableRows: [
      ["आमतौर पर एक प्रतिशत देता है।", "आमतौर पर एक विस्तृत लिखित मूल्यांकन देता है।"],
      ["अक्सर सिर्फ दो नाम इस्तेमाल करता है (जन्म तिथि के साथ या बिना)।", "व्यक्तित्व, मूल्यों और रुचियों को ध्यान में रख सकता है।"],
      ["तेज़, मज़ेदार परिणाम के लिए बना है।", "आमतौर पर ज़्यादा समय लेता है और गहराई में जाता है।"],
      ["एक हल्के, शेयर करने लायक पल के लिए बेहतरीन।", "रिश्ते पर असली आत्म-चिंतन के लिए बेहतर।"],
      ["कोई वैज्ञानिक प्रमाण नहीं दिया जाता।", "कुछ वर्ज़न मनोवैज्ञानिक शोध पर आधारित होते हैं।"],
    ],
    section6h3: "क्या लव कैलकुलेटर वैज्ञानिक रूप से सटीक है?",
    section6p2:
      "नहीं। नाम-आधारित लव प्रतिशत रोमांटिक कम्पैटिबिलिटी का कोई वैज्ञानिक रूप से प्रमाणित मापदंड नहीं है। इसे एक मनोरंजन या न्यूमेरोलॉजी-शैली के परिणाम के रूप में ही देखा जाना चाहिए — एक्सप्लोर करने में मज़ेदार, दोस्तों के साथ तुलना करने में मज़ेदार, लेकिन असली रिश्ते के फैसलों का आधार नहीं। अगर आपको असली आत्म-चिंतन चाहिए, तो मूल्यों, बातचीत की शैली और लक्ष्यों के बारे में पूछने वाला एक उचित कम्पैटिबिलिटी टेस्ट हमेशा किसी भी लव कैलकुलेटर प्रतिशत से ज़्यादा बताएगा।",

    section7Title: "न्यूमेरोलॉजी लव कम्पैटिबिलिटी कैसे कैलकुलेट करती है?",
    section7p1: "अगर आप किसी ब्लैक बॉक्स पर भरोसा करने की बजाय असली लव कैलकुलेटर के पीछे की प्रक्रिया समझना चाहते हैं, तो इसे चार आसान चरणों में समझते हैं।",
    section7h3a: "चरण 1 — अक्षरों को नंबर देना",
    section7p2: "न्यूमेरोलॉजी हर अक्षर को एक नंबर देती है, आमतौर पर 1 से 9 तक, और यह पैटर्न आगे के अक्षरों के लिए दोहराया जाता है (जैसे J, A की तरह व्यवहार करता है)। यह हर नाम के लिए एक स्थिर संख्यात्मक पहचान बनाता है।",
    section7h3b: "चरण 2 — हर नाम की गणना",
    section7p3: "नाम के हर अक्षर के नंबर को जोड़ा जाता है। उदाहरण के लिए, मान लीजिए किसी नाम के अक्षर जुड़कर 23 बनते हैं — फिर इसके अंकों को जोड़कर (2 + 3 = 5) एक अंक तक घटाया जाता है। यही अंतिम अंक उस नाम का मुख्य न्यूमेरोलॉजी नंबर बनता है।",
    section7h3c: "चरण 3 — परिणामों को मिलाना",
    section7p4: "जब हर नाम का अपना घटाया हुआ नंबर आ जाता है, कैलकुलेटर दोनों नंबरों को एक फॉर्मूले से मिलाकर अंतिम कम्पैटिबिलिटी स्कोर बनाता है, जो आमतौर पर 30% से 99% के बीच प्रतिशत में दिखाया जाता है।",
    section7h3d: "चरण 4 — क्या न्यूमेरोलॉजी एक वैज्ञानिक तरीका है?",
    section7p5: "नहीं। न्यूमेरोलॉजी एक विश्वास-आधारित प्रणाली है, न कि रिश्तों के परिणामों की भविष्यवाणी करने का कोई वैज्ञानिक रूप से स्थापित तरीका। हम यह खुलकर बताते हैं क्योंकि हम चाहते हैं कि आप इस टूल पर उसी रूप में भरोसा करें जो यह असल में है — एक मज़ेदार, ईमानदार अनुभव।",

    section8Title: "क्या लव कैलकुलेटर में नामों का क्रम मायने रखता है?",
    section8p1: "नहीं। हमारा फॉर्मूला बराबरी वाला है, यानी दोनों नामों का क्रम बदलने से प्रतिशत नहीं बदलता — चाहे आप कोई भी नाम पहले लिखें, परिणाम बिल्कुल वही रहता है।",
    section8p2: "यह एक आम सवाल है क्योंकि कुछ ऑनलाइन टूल असंतुलित तरीके से बनाए जाते हैं, जहां नाम 1 और नाम 2 को अलग तरह से देखा जाता है, जिससे क्रम बदलने पर अलग स्कोर मिलता है। हमने जानबूझकर इससे बचा है, क्योंकि जब एक मज़ेदार टूल एक ही जोड़ी के लिए दो अलग जवाब दे, तो यह भ्रमित करने वाला लग सकता है।",

    section9Title: "क्या मेरा नाम और जन्म तिथि डालना सुरक्षित है?",
    section9p1: "आपकी जानकारी सिर्फ कैलकुलेटर के बताए गए उद्देश्य के लिए इस्तेमाल होनी चाहिए — एक मज़ेदार परिणाम बनाने के लिए। हम सलाह देते हैं कि किसी भी ऑनलाइन टूल में अत्यधिक संवेदनशील जानकारी न डालें, और कुछ भी डालने से पहले वेबसाइट की",
    section9p1LinkText: "प्राइवेसी पॉलिसी",
    section9p1Post: "ज़रूर देखें ताकि पता चले डेटा स्टोर या शेयर होता है या नहीं।",
    section9p2:
      "इस साइट पर, नाम और जन्म तिथि की मुख्य गणना सीधे आपके ब्राउज़र में होती है और स्कोर बनाने के लिए इसे सर्वर पर भेजने की ज़रूरत नहीं। अलग से, यदि आपके परिणाम के साथ एक AI-जनरेटेड पर्सनलाइज़्ड नोट दिखता है, तो उस नोट को बनाने के लिए नाम और स्कोर सुरक्षित रूप से हमारे सर्वर पर भेजे जाते हैं — यह हिस्सा मुख्य गणना के लिए वैकल्पिक है और आपका डेटा हमेशा के लिए स्टोर नहीं करता।",
    section9p3: "पूरी जानकारी के लिए हमारी",
    section9p3LinkText: "प्राइवेसी पॉलिसी",
    section9p3Post: "देखें, जिसमें बताया गया है कि क्या इकट्ठा होता है और हमारे विज्ञापन व एनालिटिक्स पार्टनर कुकीज़ का उपयोग कैसे करते हैं।",

    section10Title: "क्या लव कैलकुलेटर नाम से मैरिज कम्पैटिबिलिटी जांच सकता है?",
    section10p1: "एक नाम-आधारित कैलकुलेटर, जैसे हमारा",
    section10Link: "मैरिज कम्पैटिबिलिटी कैलकुलेटर",
    section10p1Post: ", दो नामों के लिए एक न्यूमेरोलॉजी-शैली का कम्पैटिबिलिटी परिणाम दे सकता है। लेकिन यह विश्वसनीय रूप से यह नहीं बता सकता कि असली शादी सफल होगी या नहीं। यह इन असली कारकों पर निर्भर करता है:",
    section10List: ["बातचीत", "भरोसा", "साझा मूल्य", "आर्थिक अपेक्षाएं", "पारिवारिक अपेक्षाएं", "भावनात्मक कम्पैटिबिलिटी", "दीर्घकालिक लक्ष्य"],
    section10p2:
      "किसी भी मैरिज कम्पैटिबिलिटी बाय नेम परिणाम को एक मज़ेदार बातचीत की शुरुआत मानें, इन गहरे, असली-जीवन के कारकों का विकल्प नहीं। अगर दो नाम कम स्कोर करें, तो इसका असली कपल की संभावनाओं से कोई लेना-देना नहीं — और अगर दो नाम 99% स्कोर करें, तो यह पैसे, परिवार और भविष्य को लेकर ज़रूरी बातचीत का विकल्प नहीं है।",

    section11Title: "लव कैलकुलेटर और FLAMES में क्या अंतर है?",
    section11p1: "यह तुलना बार-बार सामने आती है, क्योंकि लव कैलकुलेटर बाय नेम FLAMES खोजने वाले लोग आमतौर पर यह जानना चाहते हैं कि पहले कौन सा टूल आज़माएं। ईमानदार जवाब: दोनों मज़ेदार हैं, बस परिणाम अलग तरीके से दिखाते हैं।",
    flamesTableHeaders: ["टूल", "आपको क्या मिलता है"],
    flamesTableRows: [
      ["लव कैलकुलेटर", "एक कम्पैटिबिलिटी प्रतिशत (जैसे 82%)।"],
      ["FLAMES कैलकुलेटर", "छह रिलेशनशिप कैटेगरी में से एक: फ्रेंड्स, लवर्स, अफेक्शनेट, मैरिज, एनिमीज़, या सिबलिंग्स।"],
    ],
    section11p2Pre: "अगर आप प्रतिशत की बजाय (या साथ में) FLAMES-स्टाइल गणना आज़माना चाहते हैं, तो हमारा",
    section11p2Link: "FLAMES कैलकुलेटर",
    section11p2Post: "इस्तेमाल करें — बहुत से लोग एक ही दो नामों के साथ दोनों टूल आज़माते हैं, बस तुलना करने के लिए।",

    exploreTitle: "और लव और रिलेशनशिप कैलकुलेटर एक्सप्लोर करें",
    exploreSub: "नीचे दिए गए सभी परिणाम एक ही तरीके से बनते हैं — तेज़, मुफ़्त, और सिर्फ मज़े के लिए।",

    section13Title: "क्या मैं मोबाइल पर लव कैलकुलेटर इस्तेमाल कर सकता हूं?",
    section13p1: "हाँ। यह पूरी साइट फोन, टैबलेट और डेस्कटॉप ब्राउज़र पर एक जैसी आसानी से काम करती है। आपको अलग ऐप डाउनलोड करने की ज़रूरत नहीं — फोन पर यह पेज खोलना ही किसी ऐप जैसा अनुभव देता है, बिना कोई परमिशन दिए।",
    section13p2: "इससे लव कैलकुलेटर ऐप की खोज भी कवर होती है — फिलहाल हमारा कोई डाउनलोड करने वाला ऐप नहीं है, लेकिन मोबाइल वेब वर्ज़न उतना ही तेज़ महसूस होता है, इसलिए आप इस पेज को अपनी होम स्क्रीन पर सेव कर सकते हैं।",

    section14Title: "आप लव कैलकुलेटर का उपयोग किसके लिए कर सकते हैं?",
    section14p1: "लोग नेम लव कैलकुलेटर का इस्तेमाल कई तरह की हल्की-फुल्की स्थितियों में करते हैं — नए क्रश के साथ स्कोर जांचना, कपल के नामों से परिणाम देखना, बेस्ट फ्रेंड्स के साथ तुलना करना, या सिर्फ मज़े के लिए भाई-बहन के नाम आज़माना।",
    section14p2: "यह वेलेंटाइन डे, ग्रुप चैट्स और सोशल मीडिया शेयरिंग के लिए एक लोकप्रिय विकल्प है, क्योंकि इसमें सेकंडों में परिणाम मिल जाता है और कुछ भी गंभीर नहीं मांगा जाता। क्योंकि यह टूल बराबरी वाला और प्राइवेट है, इसे जितनी बार चाहें, जितने भी नामों के साथ चाहें आज़माने में कोई नुकसान नहीं।",
    section14p3: "चाहे आप खुद जिज्ञासावश आज़मा रहे हों, या किसी दोस्त को परिणाम भेज रहे हों, लक्ष्य एक ही है: एक तेज़, मज़ेदार पल, असली ज़िंदगी का फैसला नहीं।",

    faqTitle: "लव कैलकुलेटर से जुड़े अक्सर पूछे जाने वाले सवाल",

    ctaTitle: "अपनी लव कम्पैटिबिलिटी जांचने के लिए तैयार हैं?",
    ctaP:
      "ऊपर दो नाम डालें और अपना मज़ेदार लव कम्पैटिबिलिटी प्रतिशत जानें। आप हमारे FLAMES, सोलमेट, फ्रेंडशिप और अन्य रिलेशनशिप कैलकुलेटर भी देख सकते हैं।",
    ctaBtn: "लव कम्पैटिबिलिटी कैलकुलेट करें →",
  },
};

export const faqContent = {
  en: [
    { q: "What is a love calculator by name?", a: "A love calculator by name is an online tool that generates a compatibility percentage using the names entered by two people. It's a fun, numerology-style way to explore a playful connection score." },
    { q: "Is a love calculator by name accurate?", a: "No. A name-based love percentage is not a scientifically validated measurement of romantic compatibility. It's best treated as an entertainment or numerology-style result, not a prediction." },
    { q: "How does a name love calculator calculate the percentage?", a: "Our calculator converts each letter of both names into numbers using a numerology-style system, combines those values symmetrically, and turns the result into a percentage between 30% and 99%." },
    { q: "Can I use two names without a date of birth?", a: "Yes. Date of birth is completely optional. You can calculate a result using just two names, or add both birth dates for an additional numerology-style layer." },
    { q: "Can I calculate love compatibility using date of birth?", a: "Yes. If you add both dates of birth, our tool factors them into the calculation for a more detailed, personalized-feeling result." },
    { q: "Does the order of names matter?", a: "No. Our formula is symmetrical, meaning the order of the two names does not change the percentage." },
    { q: "Is a 100% love score a guarantee of true love?", a: "No. No score from any online calculator can guarantee real-world compatibility. Treat any result as a fun starting point." },
    { q: "What is the difference between FLAMES and a love calculator?", a: "A love calculator usually produces a compatibility percentage, while FLAMES sorts two names into a relationship category." },
    { q: "Can I use the love calculator for my crush or best friend?", a: "Yes. You can select a relationship type and use the calculator purely as a fun compatibility check." },
    { q: "Can I use the love calculator on my phone?", a: "Yes. The calculator is fully mobile responsive and works the same way on phones, tablets, and desktop browsers." },
  ],
  hi: [
    { q: "लव कैलकुलेटर बाय नेम क्या है?", a: "यह एक ऑनलाइन टूल है जो दो लोगों के नामों से एक कम्पैटिबिलिटी प्रतिशत निकालता है। यह एक मज़ेदार, न्यूमेरोलॉजी-शैली का तरीका है।" },
    { q: "क्या लव कैलकुलेटर बाय नेम सटीक है?", a: "नहीं। नाम-आधारित लव प्रतिशत रोमांटिक कम्पैटिबिलिटी का कोई वैज्ञानिक मापदंड नहीं है। इसे केवल मनोरंजन के लिए देखा जाना चाहिए।" },
    { q: "यह प्रतिशत कैसे निकाला जाता है?", a: "हमारा कैलकुलेटर दोनों नामों के हर अक्षर को न्यूमेरोलॉजी-शैली में नंबर में बदलता है, उन्हें बराबरी से मिलाता है, और 30% से 99% के बीच एक प्रतिशत बनाता है।" },
    { q: "क्या मैं जन्म तिथि के बिना सिर्फ नाम से कैलकुलेट कर सकता हूं?", a: "हाँ। जन्म तिथि पूरी तरह वैकल्पिक है। आप सिर्फ दो नामों से परिणाम निकाल सकते हैं।" },
    { q: "क्या जन्म तिथि से लव कम्पैटिबिलिटी निकाली जा सकती है?", a: "हाँ। यदि आप दोनों की जन्म तिथियां जोड़ते हैं, तो हमारा टूल उन्हें गणना में शामिल करता है।" },
    { q: "क्या नामों का क्रम मायने रखता है?", a: "नहीं। हमारा फॉर्मूला बराबरी वाला है, यानी नामों का क्रम बदलने से प्रतिशत नहीं बदलता।" },
    { q: "क्या 100% स्कोर सच्चे प्यार की गारंटी है?", a: "नहीं। किसी भी ऑनलाइन कैलकुलेटर का स्कोर असली दुनिया की कम्पैटिबिलिटी की गारंटी नहीं दे सकता।" },
    { q: "FLAMES और लव कैलकुलेटर में क्या अंतर है?", a: "लव कैलकुलेटर आमतौर पर एक प्रतिशत देता है, जबकि FLAMES दो नामों को एक रिलेशनशिप कैटेगरी में बांटता है।" },
    { q: "क्या मैं इसे अपने क्रश या बेस्ट फ्रेंड के लिए इस्तेमाल कर सकता हूं?", a: "हाँ। आप एक रिलेशनशिप टाइप चुन सकते हैं और इसे सिर्फ मज़े के लिए इस्तेमाल कर सकते हैं।" },
    { q: "क्या मैं इसे मोबाइल पर इस्तेमाल कर सकता हूं?", a: "हाँ। यह कैलकुलेटर पूरी तरह मोबाइल-फ्रेंडली है और फोन, टैबलेट और डेस्कटॉप पर एक जैसा काम करता है।" },
  ],
};
