export const homeContent = {
  en: {
    h1: "Love Calculator by Name – Check Your Love Compatibility Percentage",
    tagline:
      "Enter two names to calculate a fun love compatibility percentage. You can also add dates of birth for a name-and-DOB based result.",
    trustLine:
      "A simple, private, and free love calculator designed for entertainment and compatibility exploration.",
    calculateBtn: "Calculate Love %",
    name1Label: "Name 1",
    name2Label: "Name 2",

    section2Title: "What Is a Love Calculator by Name?",
    section2p1:
      "A love calculator by name is an online tool that generates a compatibility percentage using the names entered by two people. Some calculators, including this one, also let you add a date of birth to layer in an additional numerology-style interpretation.",
    section2p2:
      "The result you receive is meant for entertainment. It is not a scientific measurement of a real relationship, and it should never replace honest conversation, trust, or time spent getting to know someone. Think of it as a playful icebreaker — a true love calculator by name that people use for fun with a crush, partner, or friend, rather than a serious predictor of the future.",

    section3Title: "What Does Your Love Calculator Score Mean?",
    scoreTableHeaders: ["Score Range", "What It Suggests"],
    scoreRows: [
      ["90% – 99%", "Exceptional Match — strong playful chemistry"],
      ["75% – 89%", "Strong Connection — good fun-scale potential"],
      ["55% – 74%", "Promising Match — a fair, balanced result"],
      ["40% – 54%", "Mixed Signals — a moderate, in-between score"],
      ["Below 40%", "Room to Grow — a lower score on this fun scale"],
    ],
    section3p:
      "These ranges exist purely to make the result easier to read at a glance. A 95% score does not scientifically mean two people are destined to be together, and a lower score does not mean the opposite. Real compatibility depends on communication, shared values, and effort — not a single number generated by a name love calculator.",

    section4Title: "How Does the Love Calculator by Name Work?",
    section4p1:
      "Our calculator uses a numerology-style approach, one of the most common methods behind any name love calculator online. It doesn't pull from a relationship database or personal history — it purely transforms the letters in each name into numbers, then combines those numbers using a set formula to produce a percentage.",
    section4h3a: "Does the Love Calculator Use Numerology?",
    section4p2:
      "Yes. Numerology assigns a numeric value to each letter of the alphabet. When you type in two names, the calculator converts every letter into its number, adds those values together, and reduces the result following a consistent formula.",
    section4h3b: "How Are Names Converted Into Numbers?",
    section4p3:
      "In a numerology-style calculation, letters can be assigned numerical values and reduced to smaller numbers. Those values can then be combined according to the calculator's formula to produce a compatibility result. This formula is not scientifically proven — it's a long-standing entertainment tradition rather than a validated method.",
    section4h3c: "Does Date of Birth Change the Result?",
    section4p4:
      "If you choose to add both dates of birth, the calculator layers in an extra numerology-style calculation based on those numbers. Leaving the date of birth fields blank still gives you a complete, name-only result — it's entirely optional.",

    section5Title: "Can You Calculate Love Compatibility by Name and Date of Birth?",
    section5p1:
      "Yes — our tool supports a love calculator by name and date of birth for anyone who wants a deeper, more personalized-feeling result. Here's exactly how it works:",
    section5Steps: [
      "Enter the first person's name.",
      "Enter the second person's name.",
      "Add both dates of birth (optional).",
      "Select a relationship type.",
      "Click Calculate.",
      "View your compatibility result instantly.",
    ],
    section5p2:
      "The core difference between a name-only calculation and a name-plus-DOB calculation is depth. A name-only result relies purely on the letters in each name. Adding a date of birth introduces a second numerology layer, which can shift the score and add another angle to the fun interpretation.",

    section6Title: "What Is the Difference Between a Love Calculator and a Compatibility Test?",
    section6p1:
      "Although the two are often searched together, they serve different purposes.",
    section6p2:
      "A love calculator usually produces a single percentage, often based purely on names. It's designed for a quick, fun result rather than deep analysis.",
    section6p3:
      "A compatibility test, on the other hand, typically considers broader factors — personality traits, values, communication style, interests, and long-term goals.",
    section6h3: "Is a Love Calculator Scientifically Accurate?",
    section6p4:
      "No. A name-based love percentage is not a scientifically validated measurement of romantic compatibility. It is best treated as an entertainment or numerology-style result.",

    section7Title: "How Does Numerology Calculate Love Compatibility by Name?",
    section7p1: "If you want to understand the mechanics behind a real love calculator, it helps to break the process into three simple steps.",
    section7h3a: "Step 1 — Assign Values to Letters",
    section7p2: "Numerology assigns each letter of the alphabet a number, usually from 1 to 9, with the pattern repeating for later letters.",
    section7h3b: "Step 2 — Calculate Each Name",
    section7p3: "Every letter's value in a name is added together, then reduced down to a single digit by adding its own digits together.",
    section7h3c: "Step 3 — Combine the Results",
    section7p4: "Once each name has its own reduced number, the calculator combines both numbers using a formula to produce the final compatibility score.",
    section7h3d: "Is Numerology a Scientific Method?",
    section7p5: "No. Numerology is a belief-based, divinatory system rather than a scientifically established method for predicting relationship outcomes.",

    section8Title: "Does the Order of Names Matter in a Love Calculator?",
    section8p: "No. Our formula is symmetrical, which means the order of the two names does not change the percentage — the same two inputs are used in the calculation regardless of which name you type first.",

    section9Title: "Is My Name and Date of Birth Safe to Enter?",
    section9p1: "Your information should only be used for the calculator's stated purpose — generating a fun compatibility result. We recommend avoiding highly sensitive personal information in any online tool.",
    section9p2: "On this site, the core name and date-of-birth calculation runs directly in your browser. If an AI-generated personalized note appears alongside your result, the names and score are sent securely to our server so that note can be generated.",

    section10Title: "Can a Love Calculator Check Marriage Compatibility by Name?",
    section10p1: "A name-based calculator can generate a numerology-style compatibility result framed around marriage. What it cannot do is reliably predict whether an actual marriage will succeed. That depends on real-world factors including:",
    section10List: ["Communication", "Trust", "Shared values", "Financial expectations", "Family expectations", "Emotional compatibility", "Long-term goals"],
    section10p2: "Treat any marriage compatibility by name result as a fun conversation starter, not a replacement for these deeper, real-life factors.",

    section11Title: "What Is the Difference Between a Love Calculator and FLAMES?",
    section11p: "A love calculator usually produces a compatibility percentage. FLAMES, on the other hand, uses two names to produce a relationship category — Friends, Love, Affection, Marriage, Enemies, or Siblings.",

    section13Title: "Can I Use the Love Calculator on Mobile?",
    section13p: "Yes. This entire site works smoothly on phones, tablets, and desktop browsers alike. You don't necessarily need a separate app — opening this page on your phone gives you the same experience, without needing to download anything.",

    section14Title: "What Can You Use a Love Calculator For?",
    section14p: "People use a name love calculator in all kinds of light-hearted situations — checking a score with a new crush, seeing what a couple's names generate together, comparing results with best friends, or even running it just for a sibling for a laugh. It's a popular pick for Valentine's Day, group chats, and social media sharing.",

    exploreTitle: "Explore More Love & Relationship Calculators",
    exploreSub: "Every result below is generated the same way — fast, free, and just for fun.",

    faqTitle: "Frequently Asked Questions About Love Calculators",

    ctaTitle: "Ready to Check Your Love Compatibility?",
    ctaP:
      "Enter two names above and discover your fun love compatibility percentage. You can also explore our FLAMES, soulmate, friendship, and other relationship calculators.",
    ctaBtn: "Calculate Love Compatibility →",
  },

  hi: {
    h1: "लव कैलकुलेटर बाय नेम – अपनी लव कम्पैटिबिलिटी प्रतिशत जानें",
    tagline:
      "दो नाम डालें और एक मज़ेदार लव कम्पैटिबिलिटी प्रतिशत निकालें। अधिक सटीक (नाम + जन्म तिथि आधारित) परिणाम के लिए जन्म तिथि भी जोड़ सकते हैं।",
    trustLine:
      "यह एक सरल, प्राइवेट और मुफ़्त लव कैलकुलेटर है, जो मनोरंजन और कम्पैटिबिलिटी एक्सप्लोर करने के लिए बनाया गया है।",
    calculateBtn: "लव % कैलकुलेट करें",
    name1Label: "नाम 1",
    name2Label: "नाम 2",

    section2Title: "लव कैलकुलेटर बाय नेम क्या है?",
    section2p1:
      "लव कैलकुलेटर बाय नेम एक ऑनलाइन टूल है जो दो लोगों के नामों का उपयोग करके एक कम्पैटिबिलिटी प्रतिशत बनाता है। कुछ कैलकुलेटर, जिनमें यह भी शामिल है, आपको जन्म तिथि जोड़ने की सुविधा भी देते हैं, जिससे एक अतिरिक्त न्यूमेरोलॉजी-शैली की व्याख्या मिलती है।",
    section2p2:
      "आपको मिलने वाला परिणाम केवल मनोरंजन के लिए है। यह किसी असली रिश्ते का वैज्ञानिक मापदंड नहीं है, और इसे कभी भी ईमानदार बातचीत, भरोसे, या किसी को जानने में लगने वाले समय की जगह नहीं लेनी चाहिए। इसे एक हल्के-फुल्के आइसब्रेकर की तरह देखें — जिसे लोग किसी क्रश, पार्टनर या दोस्त के साथ मज़े के लिए इस्तेमाल करते हैं, न कि भविष्य की गंभीर भविष्यवाणी के तौर पर।",

    section3Title: "आपके लव कैलकुलेटर स्कोर का क्या मतलब है?",
    scoreTableHeaders: ["स्कोर रेंज", "इसका क्या मतलब है"],
    scoreRows: [
      ["90% – 99%", "असाधारण मैच — मज़बूत, मज़ेदार केमिस्ट्री"],
      ["75% – 89%", "मज़बूत कनेक्शन — अच्छी संभावना"],
      ["55% – 74%", "अच्छा मैच — एक संतुलित परिणाम"],
      ["40% – 54%", "मिश्रित संकेत — एक मध्यम स्कोर"],
      ["40% से कम", "अभी सुधार की गुंजाइश — इस मज़ेदार स्केल पर एक कम स्कोर"],
    ],
    section3p:
      "ये रेंज सिर्फ परिणाम को आसानी से समझने के लिए बनाई गई हैं। 95% स्कोर का वैज्ञानिक रूप से यह मतलब नहीं है कि दो लोग एक-दूसरे के लिए बने हैं, और कम स्कोर का भी उल्टा मतलब नहीं है। असली कम्पैटिबिलिटी बातचीत, साझा मूल्यों और मेहनत पर निर्भर करती है — किसी नाम कैलकुलेटर के एक नंबर पर नहीं।",

    section4Title: "लव कैलकुलेटर बाय नेम कैसे काम करता है?",
    section4p1:
      "हमारा कैलकुलेटर एक न्यूमेरोलॉजी-शैली की विधि इस्तेमाल करता है, जो किसी भी ऑनलाइन नेम लव कैलकुलेटर के पीछे सबसे सामान्य तरीकों में से एक है। यह किसी रिलेशनशिप डेटाबेस या व्यक्तिगत इतिहास से जानकारी नहीं लेता — यह सिर्फ हर नाम के अक्षरों को नंबरों में बदलता है, फिर एक तय फॉर्मूला इस्तेमाल करके इन नंबरों को मिलाकर एक प्रतिशत निकालता है।",
    section4h3a: "क्या लव कैलकुलेटर न्यूमेरोलॉजी का उपयोग करता है?",
    section4p2:
      "हाँ। न्यूमेरोलॉजी हर अक्षर को एक नंबर देती है। जब आप दो नाम लिखते हैं, कैलकुलेटर हर अक्षर को उसके नंबर में बदलता है, उन्हें जोड़ता है, और एक तय फॉर्मूले के अनुसार परिणाम को घटाकर एक अंक तक लाता है।",
    section4h3b: "नामों को नंबरों में कैसे बदला जाता है?",
    section4p3:
      "न्यूमेरोलॉजी-शैली की गणना में, अक्षरों को नंबर दिए जाते हैं और उन्हें छोटे अंकों में घटाया जाता है। फिर इन नंबरों को कैलकुलेटर के फॉर्मूले के अनुसार मिलाकर एक कम्पैटिबिलिटी परिणाम बनाया जाता है। यह फॉर्मूला वैज्ञानिक रूप से सिद्ध नहीं है — यह एक पुरानी मनोरंजन परंपरा है, कोई प्रमाणित तरीका नहीं।",
    section4h3c: "क्या जन्म तिथि परिणाम बदल देती है?",
    section4p4:
      "यदि आप दोनों की जन्म तिथियां जोड़ते हैं, तो कैलकुलेटर उन नंबरों के आधार पर एक अतिरिक्त न्यूमेरोलॉजी गणना जोड़ता है। जन्म तिथि के फ़ील्ड खाली छोड़ने पर भी आपको एक पूरा, केवल-नाम-आधारित परिणाम मिलता है — यह पूरी तरह वैकल्पिक है।",

    section5Title: "क्या आप नाम और जन्म तिथि से लव कम्पैटिबिलिटी निकाल सकते हैं?",
    section5p1:
      "हाँ — हमारा टूल नाम और जन्म तिथि दोनों के आधार पर एक गहरे, अधिक व्यक्तिगत महसूस होने वाले परिणाम का समर्थन करता है। यह ऐसे काम करता है:",
    section5Steps: [
      "पहले व्यक्ति का नाम डालें।",
      "दूसरे व्यक्ति का नाम डालें।",
      "दोनों की जन्म तिथियां जोड़ें (वैकल्पिक)।",
      "रिलेशनशिप टाइप चुनें।",
      "कैलकुलेट पर क्लिक करें।",
      "तुरंत अपना कम्पैटिबिलिटी परिणाम देखें।",
    ],
    section5p2:
      "केवल-नाम आधारित गणना और नाम+जन्म तिथि आधारित गणना के बीच मुख्य अंतर गहराई का है। केवल-नाम परिणाम सिर्फ नाम के अक्षरों पर निर्भर करता है। जन्म तिथि जोड़ने से एक दूसरी न्यूमेरोलॉजी परत जुड़ जाती है, जो स्कोर को थोड़ा बदल सकती है।",

    section6Title: "लव कैलकुलेटर और कम्पैटिबिलिटी टेस्ट में क्या अंतर है?",
    section6p1: "हालांकि दोनों को अक्सर साथ खोजा जाता है, इनके उद्देश्य अलग-अलग हैं।",
    section6p2:
      "लव कैलकुलेटर आमतौर पर सिर्फ नामों के आधार पर एक प्रतिशत देता है। यह गहरी जांच के बजाय एक तेज़, मज़ेदार परिणाम के लिए बनाया गया है।",
    section6p3:
      "वहीं कम्पैटिबिलिटी टेस्ट आमतौर पर व्यापक कारकों को ध्यान में रखता है — व्यक्तित्व, मूल्य, बातचीत की शैली, रुचियां और दीर्घकालिक लक्ष्य।",
    section6h3: "क्या लव कैलकुलेटर वैज्ञानिक रूप से सटीक है?",
    section6p4:
      "नहीं। नाम-आधारित लव प्रतिशत रोमांटिक कम्पैटिबिलिटी का कोई वैज्ञानिक रूप से प्रमाणित मापदंड नहीं है। इसे एक मनोरंजन या न्यूमेरोलॉजी-शैली के परिणाम के रूप में ही देखा जाना चाहिए।",

    section7Title: "न्यूमेरोलॉजी लव कम्पैटिबिलिटी कैसे कैलकुलेट करती है?",
    section7p1: "किसी असली लव कैलकुलेटर के पीछे की प्रक्रिया समझने के लिए, इसे तीन आसान चरणों में समझते हैं।",
    section7h3a: "चरण 1 — अक्षरों को नंबर देना",
    section7p2: "न्यूमेरोलॉजी हर अक्षर को एक नंबर देती है, आमतौर पर 1 से 9 तक, और यह पैटर्न आगे के अक्षरों के लिए दोहराया जाता है।",
    section7h3b: "चरण 2 — हर नाम की गणना",
    section7p3: "नाम के हर अक्षर के नंबर को जोड़ा जाता है, फिर उसके अंकों को आपस में जोड़कर एक अंक तक घटाया जाता है।",
    section7h3c: "चरण 3 — परिणामों को मिलाना",
    section7p4: "जब हर नाम का अपना घटाया हुआ नंबर आ जाता है, कैलकुलेटर दोनों नंबरों को एक फॉर्मूले से मिलाकर अंतिम कम्पैटिबिलिटी स्कोर बनाता है।",
    section7h3d: "क्या न्यूमेरोलॉजी एक वैज्ञानिक तरीका है?",
    section7p5: "नहीं। न्यूमेरोलॉजी एक विश्वास-आधारित प्रणाली है, न कि रिश्तों के परिणामों की भविष्यवाणी करने का कोई वैज्ञानिक रूप से स्थापित तरीका।",

    section8Title: "क्या लव कैलकुलेटर में नामों का क्रम मायने रखता है?",
    section8p: "नहीं। हमारा फॉर्मूला बराबरी वाला है, यानी दोनों नामों का क्रम बदलने से प्रतिशत नहीं बदलता — चाहे आप कोई भी नाम पहले लिखें।",

    section9Title: "क्या मेरा नाम और जन्म तिथि डालना सुरक्षित है?",
    section9p1: "आपकी जानकारी सिर्फ कैलकुलेटर के बताए गए उद्देश्य के लिए इस्तेमाल होनी चाहिए — एक मज़ेदार परिणाम बनाने के लिए। हम सलाह देते हैं कि किसी भी ऑनलाइन टूल में अत्यधिक संवेदनशील जानकारी न डालें।",
    section9p2: "इस साइट पर, नाम और जन्म तिथि की मुख्य गणना सीधे आपके ब्राउज़र में होती है। यदि आपके परिणाम के साथ एक AI-जनरेटेड पर्सनलाइज़्ड नोट दिखता है, तो उस नोट को बनाने के लिए नाम और स्कोर सुरक्षित रूप से हमारे सर्वर पर भेजे जाते हैं।",

    section10Title: "क्या लव कैलकुलेटर नाम से मैरिज कम्पैटिबिलिटी जांच सकता है?",
    section10p1: "एक नाम-आधारित कैलकुलेटर मैरिज को लेकर एक न्यूमेरोलॉजी-शैली का कम्पैटिबिलिटी परिणाम दे सकता है। लेकिन यह विश्वसनीय रूप से यह नहीं बता सकता कि असली शादी सफल होगी या नहीं। यह इन असली कारकों पर निर्भर करता है:",
    section10List: ["बातचीत", "भरोसा", "साझा मूल्य", "आर्थिक अपेक्षाएं", "पारिवारिक अपेक्षाएं", "भावनात्मक कम्पैटिबिलिटी", "दीर्घकालिक लक्ष्य"],
    section10p2: "किसी भी मैरिज कम्पैटिबिलिटी बाय नेम परिणाम को एक मज़ेदार बातचीत की शुरुआत मानें, इन गहरे, असली-जीवन के कारकों का विकल्प नहीं।",

    section11Title: "लव कैलकुलेटर और FLAMES में क्या अंतर है?",
    section11p: "लव कैलकुलेटर आमतौर पर एक कम्पैटिबिलिटी प्रतिशत देता है। वहीं FLAMES दो नामों का उपयोग करके एक रिलेशनशिप कैटेगरी बनाता है — फ्रेंड्स, लव, अफेक्शन, मैरिज, एनिमीज़, या सिबलिंग्स।",

    section13Title: "क्या मैं मोबाइल पर लव कैलकुलेटर इस्तेमाल कर सकता हूं?",
    section13p: "हाँ। यह पूरी साइट फोन, टैबलेट और डेस्कटॉप ब्राउज़र पर एक जैसी आसानी से काम करती है। आपको अलग ऐप डाउनलोड करने की ज़रूरत नहीं — फोन पर यह पेज खोलना ही काफी है।",

    section14Title: "आप लव कैलकुलेटर का उपयोग किसके लिए कर सकते हैं?",
    section14p: "लोग नेम लव कैलकुलेटर का इस्तेमाल कई तरह की हल्की-फुल्की स्थितियों में करते हैं — नए क्रश के साथ स्कोर जांचना, कपल के नामों से परिणाम देखना, बेस्ट फ्रेंड्स के साथ तुलना करना, या सिर्फ मज़े के लिए भाई-बहन के नाम आज़माना। यह वेलेंटाइन डे, ग्रुप चैट्स और सोशल मीडिया शेयरिंग के लिए एक लोकप्रिय विकल्प है।",

    exploreTitle: "और लव और रिलेशनशिप कैलकुलेटर एक्सप्लोर करें",
    exploreSub: "नीचे दिए गए सभी परिणाम एक ही तरीके से बनते हैं — तेज़, मुफ़्त, और सिर्फ मज़े के लिए।",

    faqTitle: "लव कैलकुलेटर से जुड़े अक्सर पूछे जाने वाले सवाल",

    ctaTitle: "अपनी लव कम्पैटिबिलिटी जांचने के लिए तैयार हैं?",
    ctaP:
      "ऊपर दो नाम डालें और अपना मज़ेदार लव कम्पैटिबिलिटी प्रतिशत जानें। आप हमारे FLAMES, सोलमेट, फ्रेंडशिप और अन्य रिलेशनशिप कैलकुलेटर भी देख सकते हैं।",
    ctaBtn: "लव कम्पैटिबिलिटी कैलकुलेट करें →",
  },
};

export const faqContent = {
  en: [
    { q: "What is a love calculator by name?", a: "A love calculator by name is an online tool that generates a compatibility percentage using the names entered by two people. It's a fun, numerology-style way to explore a playful connection score." },
    { q: "Is a love calculator by name accurate?", a: "No. A name-based love percentage is not a scientifically validated measurement of romantic compatibility. It's best treated as an entertainment or numerology-style result, not a prediction." },
    { q: "How does a name love calculator calculate the percentage?", a: "Our calculator converts each letter of both names into numbers using a numerology-style system, combines those values symmetrically, and turns the result into a percentage between 30% and 99%." },
    { q: "Can I use two names without a date of birth?", a: "Yes. Date of birth is completely optional. You can calculate a result using just two names, or add both birth dates for an additional numerology-style layer." },
    { q: "Can I calculate love compatibility using date of birth?", a: "Yes. If you add both dates of birth, our tool factors them into the calculation for a more detailed, personalized-feeling result." },
    { q: "Does the order of names matter?", a: "No. Our formula is symmetrical, meaning the order of the two names does not change the percentage." },
    { q: "Is a 100% love score a guarantee of true love?", a: "No. No score from any online calculator can guarantee real-world compatibility. Treat any result as a fun starting point." },
    { q: "What is the difference between FLAMES and a love calculator?", a: "A love calculator usually produces a compatibility percentage, while FLAMES sorts two names into a relationship category." },
    { q: "Can I use the love calculator for my crush or best friend?", a: "Yes. You can select a relationship type and use the calculator purely as a fun compatibility check." },
    { q: "Can I use the love calculator on my phone?", a: "Yes. The calculator is fully mobile responsive and works the same way on phones, tablets, and desktop browsers." },
  ],
  hi: [
    { q: "लव कैलकुलेटर बाय नेम क्या है?", a: "यह एक ऑनलाइन टूल है जो दो लोगों के नामों से एक कम्पैटिबिलिटी प्रतिशत निकालता है। यह एक मज़ेदार, न्यूमेरोलॉजी-शैली का तरीका है।" },
    { q: "क्या लव कैलकुलेटर बाय नेम सटीक है?", a: "नहीं। नाम-आधारित लव प्रतिशत रोमांटिक कम्पैटिबिलिटी का कोई वैज्ञानिक मापदंड नहीं है। इसे केवल मनोरंजन के लिए देखा जाना चाहिए।" },
    { q: "यह प्रतिशत कैसे निकाला जाता है?", a: "हमारा कैलकुलेटर दोनों नामों के हर अक्षर को न्यूमेरोलॉजी-शैली में नंबर में बदलता है, उन्हें बराबरी से मिलाता है, और 30% से 99% के बीच एक प्रतिशत बनाता है।" },
    { q: "क्या मैं जन्म तिथि के बिना सिर्फ नाम से कैलकुलेट कर सकता हूं?", a: "हाँ। जन्म तिथि पूरी तरह वैकल्पिक है। आप सिर्फ दो नामों से परिणाम निकाल सकते हैं।" },
    { q: "क्या जन्म तिथि से लव कम्पैटिबिलिटी निकाली जा सकती है?", a: "हाँ। यदि आप दोनों की जन्म तिथियां जोड़ते हैं, तो हमारा टूल उन्हें गणना में शामिल करता है।" },
    { q: "क्या नामों का क्रम मायने रखता है?", a: "नहीं। हमारा फॉर्मूला बराबरी वाला है, यानी नामों का क्रम बदलने से प्रतिशत नहीं बदलता।" },
    { q: "क्या 100% स्कोर सच्चे प्यार की गारंटी है?", a: "नहीं। किसी भी ऑनलाइन कैलकुलेटर का स्कोर असली दुनिया की कम्पैटिबिलिटी की गारंटी नहीं दे सकता।" },
    { q: "FLAMES और लव कैलकुलेटर में क्या अंतर है?", a: "लव कैलकुलेटर आमतौर पर एक प्रतिशत देता है, जबकि FLAMES दो नामों को एक रिलेशनशिप कैटेगरी में बांटता है।" },
    { q: "क्या मैं इसे अपने क्रश या बेस्ट फ्रेंड के लिए इस्तेमाल कर सकता हूं?", a: "हाँ। आप एक रिलेशनशिप टाइप चुन सकते हैं और इसे सिर्फ मज़े के लिए इस्तेमाल कर सकते हैं।" },
    { q: "क्या मैं इसे मोबाइल पर इस्तेमाल कर सकता हूं?", a: "हाँ। यह कैलकुलेटर पूरी तरह मोबाइल-फ्रेंडली है और फोन, टैबलेट और डेस्कटॉप पर एक जैसा काम करता है।" },
  ],
};
