// FLAMES Calculator
export const flamesContent = {
  en: {
    title: "FLAMES Calculator by Name",
    tagline: "Enter two names and discover your FLAMES result — Friends, Lovers, Affectionate, Marriage, Enemies, or Siblings.",
    buttonLabel: "Calculate FLAMES",
    h2_1: "What Is the FLAMES Calculator?",
    p1: "The FLAMES calculator is one of the oldest and most recognizable name-based games, long before online love calculators became popular. FLAMES stands for Friends, Lovers, Affectionate, Marriage, Enemies, and Siblings — six categories that describe the type of connection between two names.",
    p2linkPre: "Many people search for a flames love calculator specifically because it feels more like a fun playground game than a serious compatibility score. If you're looking for the percentage-based experience instead, our",
    p2linkText: "Love Calculator by Name",
    p2linkPost: "covers that version.",
    h2_2: "How Does the FLAMES Method Work?",
    p3: "The classic FLAMES method compares the letters in two names, cancels out the letters that appear in both, and counts how many letters remain. That remaining count is then used to \"count off\" through the letters F-L-A-M-E-S in a loop, eliminating one letter at a time until only one is left.",
    h3_1: "Step 1 — Compare the Letters",
    p4: "Every matching letter between the two names is removed from both.",
    h3_2: "Step 2 — Count What's Left",
    p5: "Once all shared letters are cancelled, the calculator counts however many letters remain across both names combined.",
    h3_3: "Step 3 — Count Through F-L-A-M-E-S",
    p6: "Using that final number, the calculator loops through F, L, A, M, E, S, removing one letter at a time, until a single letter remains — that decides your category.",
    h2_3: "What Do the Six FLAMES Results Mean?",
    list: [
      ["Friends", "a strong, easy friendship-style connection."],
      ["Lovers", "a romantic, love-based connection."],
      ["Affectionate", "a warm, caring, gentle bond."],
      ["Marriage", "a committed, long-term style connection."],
      ["Enemies", "a clashing, rival-style energy, all in good fun."],
      ["Siblings", "a protective, sibling-like relationship."],
    ],
    p7: "None of these outcomes should be taken as a literal prediction. FLAMES is a numerology-adjacent word game passed down for generations, not a scientifically validated relationship test.",
    h2_4: "Fun Ways to Use the FLAMES Calculator",
    p8: "FLAMES works well beyond just crushes and couples. Because two of its six outcomes are Friends and Siblings, it's just as fun to run with a best friend's name, a sibling's name, or even a classmate's name for a laugh.",
    faqTitle: "Frequently Asked Questions",
    faqs: [
      { q: "What does FLAMES stand for?", a: "FLAMES stands for Friends, Lovers, Affectionate, Marriage, Enemies, and Siblings — six playful relationship categories." },
      { q: "Is FLAMES scientifically accurate?", a: "No. Like any name-based love calculator, FLAMES is an entertainment and numerology-style game, not a scientifically validated method." },
      { q: "Does the order of the two names matter in FLAMES?", a: "The FLAMES method compares the letters shared between two names, so swapping the order does not change which letters match — the result stays the same." },
      { q: "Can I use FLAMES for friends or siblings, not just crushes?", a: "Yes. FLAMES already includes Friends and Siblings as possible outcomes." },
      { q: "How is FLAMES different from a love percentage calculator?", a: "A love calculator produces a percentage, while FLAMES lands on one of six categories." },
    ],
  },
  hi: {
    title: "FLAMES कैलकुलेटर बाय नेम",
    tagline: "दो नाम डालें और अपना FLAMES परिणाम जानें — फ्रेंड्स, लवर्स, अफेक्शनेट, मैरिज, एनिमीज़, या सिबलिंग्स।",
    buttonLabel: "FLAMES कैलकुलेट करें",
    h2_1: "FLAMES कैलकुलेटर क्या है?",
    p1: "FLAMES कैलकुलेटर सबसे पुराने और सबसे पहचाने जाने वाले नाम-आधारित खेलों में से एक है, जो ऑनलाइन लव कैलकुलेटर लोकप्रिय होने से बहुत पहले से मौजूद है। FLAMES का मतलब है फ्रेंड्स, लवर्स, अफेक्शनेट, मैरिज, एनिमीज़ और सिबलिंग्स — छह कैटेगरी जो दो नामों के बीच के कनेक्शन को बताती हैं।",
    p2linkPre: "बहुत से लोग flames love calculator इसलिए खोजते हैं क्योंकि यह एक गंभीर कम्पैटिबिलिटी स्कोर से ज़्यादा एक मज़ेदार खेल जैसा महसूस होता है। अगर आपको प्रतिशत-आधारित अनुभव चाहिए, तो हमारा",
    p2linkText: "लव कैलकुलेटर बाय नेम",
    p2linkPost: "वह वर्ज़न देता है।",
    h2_2: "FLAMES तरीका कैसे काम करता है?",
    p3: "क्लासिक FLAMES तरीका दो नामों के अक्षरों की तुलना करता है, दोनों में मौजूद मिलते-जुलते अक्षरों को हटाता है, और गिनता है कि कितने अक्षर बचे हैं। फिर इस बचे हुए नंबर से F-L-A-M-E-S अक्षरों में एक-एक करके गिनती की जाती है जब तक एक अक्षर न बचे।",
    h3_1: "चरण 1 — अक्षरों की तुलना करें",
    p4: "दोनों नामों में मिलते-जुलते हर अक्षर को हटा दिया जाता है।",
    h3_2: "चरण 2 — बचे हुए को गिनें",
    p5: "जब सभी साझा अक्षर हट जाते हैं, कैलकुलेटर दोनों नामों में बचे हुए अक्षरों को गिनता है।",
    h3_3: "चरण 3 — F-L-A-M-E-S में गिनें",
    p6: "उस अंतिम नंबर का उपयोग करके, कैलकुलेटर F, L, A, M, E, S में से एक-एक अक्षर हटाता है जब तक एक अक्षर न बचे — वही आपकी कैटेगरी तय करता है।",
    h2_3: "छह FLAMES परिणामों का क्या मतलब है?",
    list: [
      ["फ्रेंड्स", "एक मज़बूत, आसान दोस्ती जैसा कनेक्शन।"],
      ["लवर्स", "एक रोमांटिक, प्यार-आधारित कनेक्शन।"],
      ["अफेक्शनेट", "एक गर्मजोशी भरा, स्नेही बंधन।"],
      ["मैरिज", "एक प्रतिबद्ध, दीर्घकालिक कनेक्शन।"],
      ["एनिमीज़", "एक टकराव वाली, प्रतिद्वंद्वी जैसी ऊर्जा, सिर्फ मज़े के लिए।"],
      ["सिबलिंग्स", "एक सुरक्षात्मक, भाई-बहन जैसा रिश्ता।"],
    ],
    p7: "इनमें से किसी भी परिणाम को शाब्दिक भविष्यवाणी नहीं मानना चाहिए। FLAMES पीढ़ियों से चला आ रहा एक न्यूमेरोलॉजी जैसा शब्द-खेल है, कोई वैज्ञानिक रूप से प्रमाणित रिश्ता परीक्षण नहीं।",
    h2_4: "FLAMES कैलकुलेटर इस्तेमाल करने के मज़ेदार तरीके",
    p8: "FLAMES सिर्फ क्रश और कपल्स के लिए नहीं है। क्योंकि इसके छह परिणामों में से दो फ्रेंड्स और सिबलिंग्स हैं, इसे बेस्ट फ्रेंड या भाई-बहन के नाम के साथ भी मज़े के लिए आज़माया जा सकता है।",
    faqTitle: "अक्सर पूछे जाने वाले सवाल",
    faqs: [
      { q: "FLAMES का मतलब क्या है?", a: "FLAMES का मतलब है फ्रेंड्स, लवर्स, अफेक्शनेट, मैरिज, एनिमीज़ और सिबलिंग्स — छह मज़ेदार रिलेशनशिप कैटेगरी।" },
      { q: "क्या FLAMES वैज्ञानिक रूप से सटीक है?", a: "नहीं। किसी भी नाम-आधारित कैलकुलेटर की तरह, FLAMES एक मनोरंजन और न्यूमेरोलॉजी-शैली का खेल है।" },
      { q: "क्या FLAMES में नामों का क्रम मायने रखता है?", a: "FLAMES तरीका दोनों नामों के साझा अक्षरों की तुलना करता है, इसलिए क्रम बदलने से परिणाम नहीं बदलता।" },
      { q: "क्या मैं FLAMES दोस्तों या भाई-बहनों के लिए इस्तेमाल कर सकता हूं?", a: "हाँ। FLAMES में पहले से ही फ्रेंड्स और सिबलिंग्स शामिल हैं।" },
      { q: "FLAMES लव प्रतिशत कैलकुलेटर से कैसे अलग है?", a: "लव कैलकुलेटर एक प्रतिशत देता है, जबकि FLAMES छह कैटेगरी में से एक पर पहुंचता है।" },
    ],
  },
};

// Soulmate Calculator
export const soulmateContent = {
  en: {
    title: "Soulmate Calculator by Name",
    tagline: "Enter two names to explore a fun, numerology-style soulmate compatibility score.",
    buttonLabel: "Calculate Soulmate Score",
    h2_1: "What Is a Soulmate Calculator?",
    p1: "A soulmate calculator is a name-based tool built around the same numerology-style math as a regular love calculator by name, but framed specifically around the idea of a soulmate-style connection.",
    p2Pre: "Just like our",
    p2Link: "main Love Calculator",
    p2Post: ", this tool accepts two names and, optionally, both dates of birth for a more detailed calculation.",
    h2_2: "How Does the Soulmate Calculator Work?",
    p3: "The calculator converts each letter of both names into a numerology-style number, combines those numbers symmetrically (so name order never matters), and translates the result into a percentage.",
    h3_1: "Is the Soulmate Score Symmetrical?",
    p4: "Yes. Entering \"Name 1\" first or \"Name 2\" first produces the exact same score, because the underlying formula treats both names equally.",
    h2_3: "Is a Soulmate Calculator Scientifically Accurate?",
    p5: "No. A soulmate calculator, like any name-based love calculator, is not a scientifically validated way to identify a soulmate. Real soulmate-level connections are built through shared experiences, trust, and time.",
    h2_4: "Soulmate Calculator vs Regular Love Calculator",
    p6Pre: "Under the hood, both tools use very similar math. People usually reach for a soulmate calculator when thinking about a deeper connection, while a general",
    p6Link: "love calculator by name",
    p6Post: "is often used for lighter, more casual curiosity.",
    h2_5: "What Should You Do With a High (or Low) Soulmate Score?",
    p7: "Enjoy it for what it is — a fun, shareable result. A high score doesn't guarantee a relationship will work, and a low score doesn't mean it won't.",
    faqTitle: "Frequently Asked Questions",
    faqs: [
      { q: "What is a soulmate calculator?", a: "A soulmate calculator is a name-based tool that generates a fun compatibility score meant to explore a soulmate-style connection." },
      { q: "Is a soulmate calculator scientifically proven?", a: "No. It's an entertainment and numerology-style tool, not a scientifically validated way to find your soulmate." },
      { q: "Can I use a soulmate calculator with just names, no birth date?", a: "Yes. Date of birth is optional." },
      { q: "How is a soulmate calculator different from a love calculator?", a: "Both use similar numerology-style math, framed around a deeper, long-term connection." },
      { q: "Does a high soulmate score mean we're meant to be together?", a: "No. Real long-term compatibility depends on communication, shared values, and effort over time." },
    ],
  },
  hi: {
    title: "सोलमेट कैलकुलेटर बाय नेम",
    tagline: "दो नाम डालें और एक मज़ेदार, न्यूमेरोलॉजी-शैली का सोलमेट कम्पैटिबिलिटी स्कोर जानें।",
    buttonLabel: "सोलमेट स्कोर कैलकुलेट करें",
    h2_1: "सोलमेट कैलकुलेटर क्या है?",
    p1: "सोलमेट कैलकुलेटर एक नाम-आधारित टूल है जो सामान्य लव कैलकुलेटर जैसी ही न्यूमेरोलॉजी गणना पर आधारित है, लेकिन इसे खासतौर पर सोलमेट-स्टाइल कनेक्शन के आइडिया के इर्द-गिर्द बनाया गया है।",
    p2Pre: "हमारे",
    p2Link: "मुख्य लव कैलकुलेटर",
    p2Post: "की तरह, यह टूल भी दो नाम लेता है और वैकल्पिक रूप से दोनों की जन्म तिथियां भी।",
    h2_2: "सोलमेट कैलकुलेटर कैसे काम करता है?",
    p3: "कैलकुलेटर दोनों नामों के हर अक्षर को न्यूमेरोलॉजी नंबर में बदलता है, उन्हें बराबरी से मिलाता है, और परिणाम को प्रतिशत में बदलता है।",
    h3_1: "क्या सोलमेट स्कोर बराबरी वाला है?",
    p4: "हाँ। \"नाम 1\" पहले डालें या \"नाम 2\" पहले, स्कोर बिल्कुल वही रहता है।",
    h2_3: "क्या सोलमेट कैलकुलेटर वैज्ञानिक रूप से सटीक है?",
    p5: "नहीं। यह सोलमेट पहचानने का कोई वैज्ञानिक तरीका नहीं है। असली सोलमेट-स्तर के कनेक्शन साझा अनुभवों, भरोसे और समय से बनते हैं।",
    h2_4: "सोलमेट कैलकुलेटर बनाम सामान्य लव कैलकुलेटर",
    p6Pre: "अंदर से, दोनों टूल लगभग एक जैसी गणना इस्तेमाल करते हैं। लोग आमतौर पर एक गहरे कनेक्शन के बारे में सोचते समय सोलमेट कैलकुलेटर चुनते हैं, जबकि सामान्य",
    p6Link: "लव कैलकुलेटर बाय नेम",
    p6Post: "हल्की जिज्ञासा के लिए इस्तेमाल होता है।",
    h2_5: "ऊंचे (या कम) सोलमेट स्कोर के साथ क्या करना चाहिए?",
    p7: "इसे वैसे ही एन्जॉय करें — एक मज़ेदार, शेयर करने लायक परिणाम। ऊंचा स्कोर रिश्ते की गारंटी नहीं देता, और कम स्कोर का मतलब नाकामी नहीं।",
    faqTitle: "अक्सर पूछे जाने वाले सवाल",
    faqs: [
      { q: "सोलमेट कैलकुलेटर क्या है?", a: "यह एक नाम-आधारित टूल है जो सोलमेट-स्टाइल कनेक्शन के लिए एक मज़ेदार कम्पैटिबिलिटी स्कोर बनाता है।" },
      { q: "क्या सोलमेट कैलकुलेटर वैज्ञानिक रूप से सिद्ध है?", a: "नहीं। यह एक मनोरंजन और न्यूमेरोलॉजी-शैली का टूल है।" },
      { q: "क्या मैं बिना जन्म तिथि के इस्तेमाल कर सकता हूं?", a: "हाँ। जन्म तिथि वैकल्पिक है।" },
      { q: "यह लव कैलकुलेटर से कैसे अलग है?", a: "दोनों समान गणना इस्तेमाल करते हैं, लेकिन यह एक गहरे, दीर्घकालिक कनेक्शन पर केंद्रित है।" },
      { q: "क्या ऊंचा स्कोर मतलब हम साथ रहने के लिए बने हैं?", a: "नहीं। असली दीर्घकालिक कम्पैटिबिलिटी बातचीत और मेहनत पर निर्भर करती है।" },
    ],
  },
};

// Marriage Compatibility Calculator
export const marriageContent = {
  en: {
    title: "Marriage Compatibility Calculator",
    tagline: "Explore a fun, name-based marriage compatibility score — for entertainment purposes.",
    buttonLabel: "Calculate Marriage Compatibility",
    h2_1: "Can a Love Calculator Check Marriage Compatibility by Name?",
    p1Pre: "A name-based calculator can generate a numerology-style compatibility result framed around marriage, using the same kind of math behind our",
    p1Link: "main Love Calculator",
    p1Post: ". What it cannot do is reliably predict whether an actual marriage will succeed.",
    h2_2: "How Does the Marriage Compatibility Score Work?",
    p2: "Both names are converted into numerology-style numbers, combined symmetrically so the order never matters, and converted into a percentage. Adding both dates of birth (optional) layers in an additional calculation.",
    h2_3: "What Actually Affects Marriage Compatibility?",
    p3: "While this calculator is fun to try, real marriage compatibility is shaped by factors no online tool can measure:",
    list: [
      ["Communication", "how openly and respectfully two people talk through disagreements."],
      ["Trust", "the foundation that lets a relationship handle stress without breaking."],
      ["Shared values", "alignment on the things that matter most day to day."],
      ["Financial expectations", "how money, saving, and spending are approached together."],
      ["Family expectations", "how each person's family and traditions fit into the relationship."],
      ["Emotional compatibility", "how well both people support each other through highs and lows."],
      ["Long-term goals", "whether both people want similar things from life, career, and family."],
    ],
    p4: "A numerology-style percentage can't capture any of this — but it can be a fun way to start a conversation about it.",
    h2_4: "Is This Tool the Same as a Regular Love Calculator?",
    p5Pre: "The underlying formula is similar to our",
    p5Link: "Love Calculator by Name",
    p5Post: ". The difference is framing — this version is designed for people specifically curious about a marriage-style compatibility question.",
    faqTitle: "Frequently Asked Questions",
    faqs: [
      { q: "Can a name calculator really predict marriage success?", a: "No. It can generate a fun numerology-style score, but cannot reliably predict a real marriage's success." },
      { q: "Is marriage compatibility by name scientifically backed?", a: "No. This is an entertainment and numerology-style tool." },
      { q: "Do I need both dates of birth?", a: "No, dates of birth are optional." },
      { q: "What real factors affect marriage compatibility?", a: "Communication, trust, shared values, financial and family expectations, emotional compatibility, and long-term goals." },
      { q: "Is this the same as a love percentage calculator?", a: "It uses similar math to our main Love Calculator, framed around a marriage-style question." },
    ],
  },
  hi: {
    title: "मैरिज कम्पैटिबिलिटी कैलकुलेटर",
    tagline: "एक मज़ेदार, नाम-आधारित मैरिज कम्पैटिबिलिटी स्कोर एक्सप्लोर करें — केवल मनोरंजन के लिए।",
    buttonLabel: "मैरिज कम्पैटिबिलिटी कैलकुलेट करें",
    h2_1: "क्या लव कैलकुलेटर नाम से मैरिज कम्पैटिबिलिटी जांच सकता है?",
    p1Pre: "एक नाम-आधारित कैलकुलेटर हमारे",
    p1Link: "मुख्य लव कैलकुलेटर",
    p1Post: "जैसी ही गणना का उपयोग करके मैरिज को लेकर एक न्यूमेरोलॉजी-शैली का परिणाम दे सकता है। लेकिन यह विश्वसनीय रूप से नहीं बता सकता कि असली शादी सफल होगी या नहीं।",
    h2_2: "मैरिज कम्पैटिबिलिटी स्कोर कैसे काम करता है?",
    p2: "दोनों नामों को न्यूमेरोलॉजी नंबरों में बदला जाता है, बराबरी से मिलाया जाता है, और प्रतिशत में बदला जाता है। दोनों जन्म तिथियां जोड़ने (वैकल्पिक) से एक अतिरिक्त गणना जुड़ जाती है।",
    h2_3: "असल में मैरिज कम्पैटिबिलिटी को क्या प्रभावित करता है?",
    p3: "यह कैलकुलेटर आज़माने में मज़ेदार है, लेकिन असली मैरिज कम्पैटिबिलिटी उन कारकों से बनती है जिन्हें कोई ऑनलाइन टूल नहीं माप सकता:",
    list: [
      ["बातचीत", "दो लोग असहमति को कितनी खुले और सम्मानपूर्वक तरीके से सुलझाते हैं।"],
      ["भरोसा", "वह नींव जो रिश्ते को तनाव में भी टूटने नहीं देती।"],
      ["साझा मूल्य", "रोज़मर्रा में सबसे महत्वपूर्ण चीज़ों पर सहमति।"],
      ["आर्थिक अपेक्षाएं", "पैसे, बचत और खर्च को साथ मिलकर कैसे संभाला जाता है।"],
      ["पारिवारिक अपेक्षाएं", "हर व्यक्ति का परिवार और परंपराएं रिश्ते में कैसे फिट होती हैं।"],
      ["भावनात्मक कम्पैटिबिलिटी", "दोनों एक-दूसरे को उतार-चढ़ाव में कितना सहारा देते हैं।"],
      ["दीर्घकालिक लक्ष्य", "क्या दोनों जीवन, करियर और परिवार से एक जैसी चीज़ें चाहते हैं।"],
    ],
    p4: "एक न्यूमेरोलॉजी प्रतिशत इनमें से कुछ भी नहीं माप सकता — लेकिन यह इस बारे में बातचीत शुरू करने का एक मज़ेदार तरीका हो सकता है।",
    h2_4: "क्या यह टूल सामान्य लव कैलकुलेटर जैसा ही है?",
    p5Pre: "इसका फॉर्मूला हमारे",
    p5Link: "लव कैलकुलेटर बाय नेम",
    p5Post: "जैसा ही है। फर्क सिर्फ फ्रेमिंग का है — यह वर्ज़न खासतौर पर मैरिज-स्टाइल सवाल के लिए बनाया गया है।",
    faqTitle: "अक्सर पूछे जाने वाले सवाल",
    faqs: [
      { q: "क्या नाम कैलकुलेटर सच में शादी की सफलता बता सकता है?", a: "नहीं। यह एक मज़ेदार स्कोर दे सकता है, लेकिन असली शादी की सफलता की गारंटी नहीं दे सकता।" },
      { q: "क्या नाम से मैरिज कम्पैटिबिलिटी वैज्ञानिक है?", a: "नहीं। यह एक मनोरंजन और न्यूमेरोलॉजी-शैली का टूल है।" },
      { q: "क्या दोनों की जन्म तिथि ज़रूरी है?", a: "नहीं, जन्म तिथि वैकल्पिक है।" },
      { q: "मैरिज कम्पैटिबिलिटी को असल में क्या प्रभावित करता है?", a: "बातचीत, भरोसा, साझा मूल्य, आर्थिक और पारिवारिक अपेक्षाएं, भावनात्मक कम्पैटिबिलिटी, और दीर्घकालिक लक्ष्य।" },
      { q: "क्या यह लव प्रतिशत कैलकुलेटर जैसा ही है?", a: "यह हमारे मुख्य लव कैलकुलेटर जैसी ही गणना इस्तेमाल करता है, बस मैरिज-केंद्रित है।" },
    ],
  },
};

// Friendship Calculator
export const friendshipContent = {
  en: {
    title: "Friendship Calculator by Name",
    tagline: "Enter two names to check a fun, numerology-style friendship compatibility score.",
    buttonLabel: "Calculate Friendship Score",
    h2_1: "What Is a Friendship Calculator?",
    p1: "A friendship calculator uses the same kind of numerology-style formula as a typical love calculator by name, but reframes the result around platonic friendship rather than romance.",
    h2_2: "How Does the Friendship Score Work?",
    p2: "Both names are converted into numbers using a numerology-style system, combined symmetrically, and turned into a percentage between 30% and 99%.",
    h2_3: "Is the Friendship Calculator Scientifically Accurate?",
    p3Pre: "No. This is an entertainment and numerology-style tool, just like our",
    p3Link: "main Love Calculator",
    p3Post: ". Real friendships are built on trust, shared experiences, and honesty.",
    h2_4: "Fun Ways to Use the Friendship Calculator",
    p4Pre: "Try it with a best friend, a sibling, a group chat, or even a new classmate. If you want a different framing on the same two names, our",
    p4Link: "FLAMES Calculator",
    p4Post: "includes a dedicated \"Friends\" outcome too.",
    faqTitle: "Frequently Asked Questions",
    faqs: [
      { q: "What is a friendship calculator?", a: "A friendship calculator is a name-based tool that generates a fun compatibility percentage focused on friendship." },
      { q: "Is the friendship calculator accurate?", a: "No. It's a numerology-style entertainment tool, not a scientifically validated friendship test." },
      { q: "Can I use this for a best friend or sibling?", a: "Yes. It works well for best friends, siblings, classmates, or any two names." },
      { q: "Does the order of names change the friendship score?", a: "No. The formula is symmetrical." },
      { q: "How is this different from the main Love Calculator?", a: "Same formula, framed around platonic friendship instead of romance." },
    ],
  },
  hi: {
    title: "फ्रेंडशिप कैलकुलेटर बाय नेम",
    tagline: "दो नाम डालें और एक मज़ेदार, न्यूमेरोलॉजी-शैली का फ्रेंडशिप कम्पैटिबिलिटी स्कोर जानें।",
    buttonLabel: "फ्रेंडशिप स्कोर कैलकुलेट करें",
    h2_1: "फ्रेंडशिप कैलकुलेटर क्या है?",
    p1: "फ्रेंडशिप कैलकुलेटर एक सामान्य लव कैलकुलेटर जैसा ही न्यूमेरोलॉजी फॉर्मूला इस्तेमाल करता है, लेकिन इसे रोमांस की बजाय दोस्ती पर केंद्रित किया गया है।",
    h2_2: "फ्रेंडशिप स्कोर कैसे काम करता है?",
    p2: "दोनों नामों को न्यूमेरोलॉजी नंबरों में बदला जाता है, बराबरी से मिलाया जाता है, और 30% से 99% के बीच प्रतिशत बनाया जाता है।",
    h2_3: "क्या फ्रेंडशिप कैलकुलेटर वैज्ञानिक रूप से सटीक है?",
    p3Pre: "नहीं। यह हमारे",
    p3Link: "मुख्य लव कैलकुलेटर",
    p3Post: "जैसा ही एक मनोरंजन और न्यूमेरोलॉजी-शैली का टूल है। असली दोस्ती भरोसे, साझा अनुभवों और ईमानदारी से बनती है।",
    h2_4: "फ्रेंडशिप कैलकुलेटर इस्तेमाल करने के मज़ेदार तरीके",
    p4Pre: "इसे बेस्ट फ्रेंड, भाई-बहन, ग्रुप चैट, या किसी नए क्लासमेट के साथ आज़माएं। अगर आप उन्हीं दो नामों के साथ कुछ अलग करना चाहते हैं, तो हमारा",
    p4Link: "FLAMES कैलकुलेटर",
    p4Post: "में भी एक \"फ्रेंड्स\" परिणाम शामिल है।",
    faqTitle: "अक्सर पूछे जाने वाले सवाल",
    faqs: [
      { q: "फ्रेंडशिप कैलकुलेटर क्या है?", a: "यह एक नाम-आधारित टूल है जो दोस्ती पर केंद्रित एक मज़ेदार कम्पैटिबिलिटी प्रतिशत बनाता है।" },
      { q: "क्या फ्रेंडशिप कैलकुलेटर सटीक है?", a: "नहीं। यह एक न्यूमेरोलॉजी-शैली का मनोरंजन टूल है।" },
      { q: "क्या मैं इसे बेस्ट फ्रेंड या भाई-बहन के लिए इस्तेमाल कर सकता हूं?", a: "हाँ। यह बेस्ट फ्रेंड्स, भाई-बहन, क्लासमेट्स के लिए भी अच्छे से काम करता है।" },
      { q: "क्या नामों का क्रम स्कोर बदलता है?", a: "नहीं। फॉर्मूला बराबरी वाला है।" },
      { q: "यह मुख्य लव कैलकुलेटर से कैसे अलग है?", a: "वही फॉर्मूला, बस दोस्ती पर केंद्रित है, रोमांस पर नहीं।" },
    ],
  },
};

// Crush Calculator
export const crushContent = {
  en: {
    title: "Crush Calculator by Name",
    tagline: "Enter your name and your crush's name for a fun, private compatibility score.",
    name1Label: "Your Name",
    name2Label: "Your Crush's Name",
    buttonLabel: "Calculate Crush Score",
    h2_1: "What Is a Crush Calculator?",
    p1Pre: "A crush calculator is simply a love calculator by name framed around one of the most common reasons people search for these tools. It uses the same numerology-style formula as our",
    p1Link: "main Love Calculator",
    p1Post: ", just with labels that make sense for this specific, very relatable situation.",
    h2_2: "Is It Private?",
    p2: "Yes. The calculation runs directly in your browser, and nothing about your crush's name or your result is sent to them or shared publicly unless you personally choose to share it.",
    h2_3: "How Is the Crush Score Calculated?",
    p3: "Both names are converted into numerology-style numbers, combined symmetrically, and turned into a percentage between 30% and 99%. You can optionally add both birth dates.",
    h2_4: "Should I Take the Result Seriously?",
    p4: "Not literally. A crush calculator is an entertainment and numerology-style tool — a fun way to pass a few minutes, not a scientific signal about whether your crush likes you back.",
    faqTitle: "Frequently Asked Questions",
    faqs: [
      { q: "What is a crush calculator?", a: "A crush calculator is a name-based tool that generates a fun compatibility percentage between you and someone you have a crush on." },
      { q: "Is the crush calculator accurate?", a: "No. It's a numerology-style entertainment tool, not a scientifically validated prediction." },
      { q: "Will my crush know I used this calculator?", a: "No. The calculator runs privately in your browser." },
      { q: "Can I use the crush calculator more than once?", a: "Yes. You can run it as many times as you like." },
      { q: "What's the difference between this and the main love calculator?", a: "Same formula, framed specifically around a crush scenario." },
    ],
  },
  hi: {
    title: "क्रश कैलकुलेटर बाय नेम",
    tagline: "अपना नाम और अपने क्रश का नाम डालें और एक मज़ेदार, प्राइवेट कम्पैटिबिलिटी स्कोर पाएं।",
    name1Label: "आपका नाम",
    name2Label: "आपके क्रश का नाम",
    buttonLabel: "क्रश स्कोर कैलकुलेट करें",
    h2_1: "क्रश कैलकुलेटर क्या है?",
    p1Pre: "क्रश कैलकुलेटर बस एक लव कैलकुलेटर है जो उस सबसे आम वजह पर केंद्रित है जिसके लिए लोग ऐसे टूल खोजते हैं। यह हमारे",
    p1Link: "मुख्य लव कैलकुलेटर",
    p1Post: "जैसा ही न्यूमेरोलॉजी फॉर्मूला इस्तेमाल करता है, बस लेबल इस खास स्थिति के हिसाब से हैं।",
    h2_2: "क्या यह प्राइवेट है?",
    p2: "हाँ। गणना सीधे आपके ब्राउज़र में होती है, और आपके क्रश के नाम या परिणाम के बारे में कुछ भी उन्हें नहीं भेजा जाता जब तक आप खुद शेयर न करें।",
    h2_3: "क्रश स्कोर कैसे कैलकुलेट होता है?",
    p3: "दोनों नामों को न्यूमेरोलॉजी नंबरों में बदला जाता है, बराबरी से मिलाया जाता है, और 30% से 99% के बीच प्रतिशत बनाया जाता है।",
    h2_4: "क्या मुझे परिणाम को गंभीरता से लेना चाहिए?",
    p4: "शाब्दिक रूप से नहीं। क्रश कैलकुलेटर एक मनोरंजन टूल है — कुछ मिनट बिताने का एक मज़ेदार तरीका, यह कोई वैज्ञानिक संकेत नहीं कि आपका क्रश आपको पसंद करता है या नहीं।",
    faqTitle: "अक्सर पूछे जाने वाले सवाल",
    faqs: [
      { q: "क्रश कैलकुलेटर क्या है?", a: "यह एक नाम-आधारित टूल है जो आपके और आपके क्रश के बीच एक मज़ेदार कम्पैटिबिलिटी प्रतिशत बनाता है।" },
      { q: "क्या क्रश कैलकुलेटर सटीक है?", a: "नहीं। यह एक न्यूमेरोलॉजी-शैली का मनोरंजन टूल है।" },
      { q: "क्या मेरे क्रश को पता चलेगा कि मैंने यह इस्तेमाल किया?", a: "नहीं। कैलकुलेटर आपके ब्राउज़र में प्राइवेट तरीके से चलता है।" },
      { q: "क्या मैं इसे कई बार इस्तेमाल कर सकता हूं?", a: "हाँ। आप इसे जितनी बार चाहें इस्तेमाल कर सकते हैं।" },
      { q: "यह मुख्य लव कैलकुलेटर से कैसे अलग है?", a: "वही फॉर्मूला, बस क्रश की स्थिति पर केंद्रित है।" },
    ],
  },
};
